In [1]:
import pandas as pd
file="C:/Users/ashwy/Downloads/male_players.csv"
df=pd.read_csv(file)

print(df.info())
display(df.head())

C:\Users\ashwy\AppData\Local\Temp\ipykernel_37344\1619314098.py:3: DtypeWarning: Columns (0: gk) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(file)

<class 'pandas.DataFrame'>
RangeIndex: 10003590 entries, 0 to 10003589
Columns: 110 entries, player_id to player_face_url
dtypes: float64(18), int64(45), object(1), str(46)
memory usage: 11.1+ GB
None

,player_id,player_url,fifa_version,fifa_update,fifa_update_date,short_name,long_name,player_positions,overall,potential,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url
0,158023,/player/158023/lionel-messi/230009,23,9,2023-01-13,L. Messi,Lionel Andrés Messi Cuccittini,RW,91,91,...,63+3,63+3,64+3,59+3,50+3,50+3,50+3,59+3,19+3,https://cdn.sofifa.net/players/158/023/23_120.png
1,165153,/player/165153/karim-benzema/230009,23,9,2023-01-13,K. Benzema,Karim Benzema,"CF, ST",91,91,...,64+3,64+3,64+3,60+3,55+3,55+3,55+3,60+3,18+3,https://cdn.sofifa.net/players/165/153/23_120.png
2,188545,/player/188545/robert-lewandowski/230009,23,9,2023-01-13,R. Lewandowski,Robert Lewandowski,ST,91,91,...,66+3,66+3,64+3,61+3,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/23_120.png
3,192985,/player/192985/kevin-de-bruyne/230009,23,9,2023-01-13,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,...,79+3,79+3,78+3,74+3,68+3,68+3,68+3,74+3,21+3,https://cdn.sofifa.net/players/192/985/23_120.png
4,231747,/player/231747/kylian-mbappe/230009,23,9,2023-01-13,K. Mbappé,Kylian Mbappé Lottin,"ST, LW",91,95,...,63+3,63+3,67+3,63+3,54+3,54+3,54+3,63+3,18+3,https://cdn.sofifa.net/players/231/747/23_120.png

In [2]:
print(df['fifa_version'].dtype)

int64

In [3]:
print(len(df[df['fifa_version']==23]))

166674

In [6]:
season_23=df[df['fifa_version']==23]
season_23.to_csv('data/sofifa/newdata/players/RAW/fc23.csv',index=False)

## RAW FILES

In [2]:
#File Paths
import pandas as pd
RAW_PLAYERS='data/sofifa/newdata/players/RAW/'
fc26=pd.read_csv(f'{RAW_PLAYERS}FC26.csv')
fc25=pd.read_csv(f'{RAW_PLAYERS}fc25.csv')
fc24=pd.read_csv(f'{RAW_PLAYERS}FC24.csv')
fifa23=pd.read_csv(f'{RAW_PLAYERS}fc23.csv')
fifa22=pd.read_csv(f'{RAW_PLAYERS}players_22.csv')
fifa21=pd.read_csv(f'{RAW_PLAYERS}players_21.csv')
fifa20=pd.read_csv(f'{RAW_PLAYERS}players_20.csv')

df_list=[fc26,fc25,fc24,fifa23,fifa22,fifa21,fifa20]
for df in df_list:
    print(df.shape)
    print(df.columns.tolist())
    print('-'*50)

C:\Users\ashwy\AppData\Local\Temp\ipykernel_9376\1086894509.py:4: DtypeWarning: Columns (0: player_tags) have mixed types. Specify dtype option on import or set low_memory=False.
  fc26=pd.read_csv(f'{RAW_PLAYERS}FC26.csv')
C:\Users\ashwy\AppData\Local\Temp\ipykernel_9376\1086894509.py:5: DtypeWarning: Columns (0: international_reputation) have mixed types. Specify dtype option on import or set low_memory=False.
  fc25=pd.read_csv(f'{RAW_PLAYERS}fc25.csv')
C:\Users\ashwy\AppData\Local\Temp\ipykernel_9376\1086894509.py:6: DtypeWarning: Columns (0: weak_foot, 1: skill_moves, 2: country_name, 3: country_league_id, 4: country_league_name, 5: country_flag, 6: country_position, 7: gk_positioning) have mixed types. Specify dtype option on import or set low_memory=False.
  fc24=pd.read_csv(f'{RAW_PLAYERS}FC24.csv')
C:\Users\ashwy\AppData\Local\Temp\ipykernel_9376\1086894509.py:8: DtypeWarning: Columns (0: nation_position, 1: nation_logo_url) have mixed types. Specify dtype option on import or set low_memory=False.
  fifa22=pd.read_csv(f'{RAW_PLAYERS}players_22.csv')

(18405, 110)
['player_id', 'player_url', 'fifa_version', 'fifa_update', 'fifa_update_date', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'league_id', 'league_name', 'league_level', 'club_team_id', 'club_name', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined_date', 'club_contract_valid_until_year', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url']
--------------------------------------------------
(18205, 76)
['player_id', 'version', 'name', 'full_name', 'description', 'image', 'height_cm', 'weight_kg', 'dob', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'club_id', 'club_name', 'club_league_id', 'club_league_name', 'club_logo', 'club_rating', 'club_position', 'club_kit_number', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'country_league_id', 'country_league_name', 'country_flag', 'country_rating', 'country_position', 'country_kit_number', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'play_styles']
--------------------------------------------------
(18331, 76)
['player_id', 'version', 'name', 'full_name', 'description', 'image', 'height_cm', 'weight_kg', 'dob', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'club_id', 'club_name', 'club_league_id', 'club_league_name', 'club_logo', 'club_rating', 'club_position', 'club_kit_number', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'country_league_id', 'country_league_name', 'country_flag', 'country_rating', 'country_position', 'country_kit_number', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'play_styles']
--------------------------------------------------
(166674, 110)
['player_id', 'player_url', 'fifa_version', 'fifa_update', 'fifa_update_date', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'league_id', 'league_name', 'league_level', 'club_team_id', 'club_name', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined_date', 'club_contract_valid_until_year', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url']
--------------------------------------------------
(19239, 110)
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url']
--------------------------------------------------
(18944, 110)
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url']
--------------------------------------------------
(18483, 110)
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url']
--------------------------------------------------

In [3]:
import pandas as pd

def prune_datasets(df_list):
    """
    Strips noise, text, and granular positional ratings from a list of dataframes.
    """
    # Phase 1 Drop Targets
    url_image_cols = [
        'player_url', 'player_face_url', 'club_logo_url', 
        'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'image'
    ]
    
    text_cols = ['description']
    
    positional_ratings = [
        'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 
        'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 
        'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk'
    ]
    
    # Combine all targets into a single master drop list
    cols_to_drop = url_image_cols + text_cols + positional_ratings
    
    # Execute drop across all dataframes in-place
    for i in range(len(df_list)):
        df_list[i].drop(columns=cols_to_drop, errors='ignore', inplace=True)
        print(f"Dataset {i+1} reduced to {len(df_list[i].columns)} columns.")
        
    return df_list

df_list = prune_datasets(df_list)

for df in df_list:
    print(df.shape)
    print(df.columns.tolist())
    print('-'*50)

Dataset 1 reduced to 81 columns.
Dataset 2 reduced to 74 columns.
Dataset 3 reduced to 74 columns.
Dataset 4 reduced to 81 columns.
Dataset 5 reduced to 77 columns.
Dataset 6 reduced to 77 columns.
Dataset 7 reduced to 77 columns.
(18405, 81)
['player_id', 'fifa_version', 'fifa_update', 'fifa_update_date', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'league_id', 'league_name', 'league_level', 'club_team_id', 'club_name', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined_date', 'club_contract_valid_until_year', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']
--------------------------------------------------
(18205, 74)
['player_id', 'version', 'name', 'full_name', 'height_cm', 'weight_kg', 'dob', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'club_id', 'club_name', 'club_league_id', 'club_league_name', 'club_logo', 'club_rating', 'club_position', 'club_kit_number', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'country_league_id', 'country_league_name', 'country_flag', 'country_rating', 'country_position', 'country_kit_number', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'play_styles']
--------------------------------------------------
(18331, 74)
['player_id', 'version', 'name', 'full_name', 'height_cm', 'weight_kg', 'dob', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'club_id', 'club_name', 'club_league_id', 'club_league_name', 'club_logo', 'club_rating', 'club_position', 'club_kit_number', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'country_league_id', 'country_league_name', 'country_flag', 'country_rating', 'country_position', 'country_kit_number', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'play_styles']
--------------------------------------------------
(166674, 81)
['player_id', 'fifa_version', 'fifa_update', 'fifa_update_date', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'league_id', 'league_name', 'league_level', 'club_team_id', 'club_name', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined_date', 'club_contract_valid_until_year', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']
--------------------------------------------------
(19239, 77)
['sofifa_id', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']
--------------------------------------------------
(18944, 77)
['sofifa_id', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']
--------------------------------------------------
(18483, 77)
['sofifa_id', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']
--------------------------------------------------

In [4]:
import pandas as pd

def standardize_schema(df_list):
    """
    Unifies dataset columns to the concise 76-column schema naming convention.
    """
    # 1. Explicit mapping for core identifiers, financials, and team data
    master_mapping = {
        'sofifa_id': 'player_id',
        'short_name': 'name',
        'long_name': 'full_name',
        'player_positions': 'positions',
        'overall': 'overall_rating',
        'value_eur': 'value',
        'wage_eur': 'wage',
        'release_clause_eur': 'release_clause',
        'club_team_id': 'club_id',
        'league_name': 'club_league_name',
        'club_jersey_number': 'club_kit_number',
        'club_joined_date': 'club_joined',
        'club_contract_valid_until_year': 'club_contract_valid_until',
        'nationality_id': 'country_id',
        'nationality_name': 'country_name',
        'nation_jersey_number': 'country_kit_number',
        'player_tags': 'specialities',
        'player_traits': 'play_styles',
        # Edge cases explicitly defined
        'defending_marking_awareness': 'defensive_awareness',
        'goalkeeping_diving': 'gk_diving',
        'goalkeeping_handling': 'gk_handling',
        'goalkeeping_kicking': 'gk_kicking',
        'goalkeeping_positioning': 'gk_positioning',
        'goalkeeping_reflexes': 'gk_reflexes',
        'goalkeeping_speed': 'gk_speed'
    }

    # 2. Prefixes to dynamically strip from granular attributes
    prefixes_to_strip = [
        'attacking_', 'skill_', 'movement_', 
        'power_', 'mentality_', 'defending_'
    ]

    for i, df in enumerate(df_list):
        # NEW FIX: Isolate the macro dribbling stat before stripping prefixes
        if 'skill_dribbling' in df.columns and 'dribbling' in df.columns:
            df.rename(columns={'dribbling': 'macro_dribbling'}, inplace=True)

        # Apply the explicit master dictionary
        df.rename(columns=master_mapping, inplace=True)
        
        # Dynamically strip the prefixes from the remaining 110-col schemas
        new_columns = {}
        for col in df.columns:
            for prefix in prefixes_to_strip:
                if col.startswith(prefix):
                    new_columns[col] = col.replace(prefix, '')
                    break # Stop checking prefixes once a match is found
        
        df.rename(columns=new_columns, inplace=True)
        print(f"Dataset {i+1} schema standardized. Current column count: {len(df.columns)}")

    return df_list


df_list = standardize_schema(df_list)
def df_check():
    for df in df_list:
        print(df.shape)
        print(df.columns.tolist())
        print('-'*50)

df_check()

Dataset 1 schema standardized. Current column count: 81
Dataset 2 schema standardized. Current column count: 74
Dataset 3 schema standardized. Current column count: 74
Dataset 4 schema standardized. Current column count: 81
Dataset 5 schema standardized. Current column count: 77
Dataset 6 schema standardized. Current column count: 77
Dataset 7 schema standardized. Current column count: 77
(18405, 81)
['player_id', 'fifa_version', 'fifa_update', 'fifa_update_date', 'name', 'full_name', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'age', 'dob', 'height_cm', 'weight_kg', 'league_id', 'club_league_name', 'league_level', 'club_id', 'club_name', 'club_position', 'club_kit_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'nation_team_id', 'nation_position', 'country_kit_number', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'play_styles', 'pace', 'shooting', 'passing', 'macro_dribbling', 'defending', 'physic', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'gk_speed']
--------------------------------------------------
(18205, 74)
['player_id', 'version', 'name', 'full_name', 'height_cm', 'weight_kg', 'dob', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'club_id', 'club_name', 'club_league_id', 'club_league_name', 'club_logo', 'club_rating', 'club_position', 'club_kit_number', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'country_league_id', 'country_league_name', 'country_flag', 'country_rating', 'country_position', 'country_kit_number', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'play_styles']
--------------------------------------------------
(18331, 74)
['player_id', 'version', 'name', 'full_name', 'height_cm', 'weight_kg', 'dob', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'club_id', 'club_name', 'club_league_id', 'club_league_name', 'club_logo', 'club_rating', 'club_position', 'club_kit_number', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'country_league_id', 'country_league_name', 'country_flag', 'country_rating', 'country_position', 'country_kit_number', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'play_styles']
--------------------------------------------------
(166674, 81)
['player_id', 'fifa_version', 'fifa_update', 'fifa_update_date', 'name', 'full_name', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'age', 'dob', 'height_cm', 'weight_kg', 'league_id', 'club_league_name', 'league_level', 'club_id', 'club_name', 'club_position', 'club_kit_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'nation_team_id', 'nation_position', 'country_kit_number', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'play_styles', 'pace', 'shooting', 'passing', 'macro_dribbling', 'defending', 'physic', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'gk_speed']
--------------------------------------------------
(19239, 77)
['player_id', 'name', 'full_name', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'age', 'dob', 'height_cm', 'weight_kg', 'club_id', 'club_name', 'club_league_name', 'league_level', 'club_position', 'club_kit_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'nation_team_id', 'nation_position', 'country_kit_number', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'play_styles', 'pace', 'shooting', 'passing', 'macro_dribbling', 'defending', 'physic', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'gk_speed']
--------------------------------------------------
(18944, 77)
['player_id', 'name', 'full_name', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'age', 'dob', 'height_cm', 'weight_kg', 'club_id', 'club_name', 'club_league_name', 'league_level', 'club_position', 'club_kit_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'nation_team_id', 'nation_position', 'country_kit_number', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'play_styles', 'pace', 'shooting', 'passing', 'macro_dribbling', 'defending', 'physic', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'gk_speed']
--------------------------------------------------
(18483, 77)
['player_id', 'name', 'full_name', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'age', 'dob', 'height_cm', 'weight_kg', 'club_id', 'club_name', 'club_league_name', 'league_level', 'club_position', 'club_kit_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'nation_team_id', 'nation_position', 'country_kit_number', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'play_styles', 'pace', 'shooting', 'passing', 'macro_dribbling', 'defending', 'physic', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'gk_speed']
--------------------------------------------------

In [5]:
def inject_season_tags(df_list):
    """
    Injects a temporal 'season' column into each dataframe to track 
    chronological data before concatenation.
    """
    # Define the season labels matching the exact order of your dataframes
    # (Ordered from newest to oldest: 25/26 -> 19/20)
    season_labels = [
        '2025-2026', '2024-2025', '2023-2024', 
        '2022-2023', '2021-2022', '2020-2021', '2019-2020'
    ]
    
    # Iterate through the list and broadcast the string to a new column
    for i, df in enumerate(df_list):
        df['season'] = season_labels[i]
        print(f"Dataset {i+1} temporally tagged as: {season_labels[i]}")
        
    return df_list

# Execution:
df_list = inject_season_tags(df_list)

Dataset 1 temporally tagged as: 2025-2026
Dataset 2 temporally tagged as: 2024-2025
Dataset 3 temporally tagged as: 2023-2024
Dataset 4 temporally tagged as: 2022-2023
Dataset 5 temporally tagged as: 2021-2022
Dataset 6 temporally tagged as: 2020-2021
Dataset 7 temporally tagged as: 2019-2020

In [6]:
for df in df_list:
    display(df.head())

,player_id,fifa_version,fifa_update,fifa_update_date,name,full_name,positions,overall_rating,potential,value,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,gk_speed,season
0,252371,26,4,2025-09-19,J. Bellingham,Jude Victor William Bellingham,"CAM, CM",90,94,174500000,...,77,79,77,14,11,10,5,8,NaN,2025-2026
1,239053,26,4,2025-09-19,F. Valverde,Federico Santiago Valverde Dipetta,"CM, CDM, RB",89,90,120500000,...,82,87,86,6,10,6,15,8,NaN,2025-2026
2,212622,26,4,2025-09-19,J. Kimmich,Joshua Walter Kimmich,"CDM, RB, CM",89,89,86000000,...,82,86,85,8,15,7,15,15,NaN,2025-2026
3,235212,26,4,2025-09-19,A. Hakimi,Achraf Hakimi Mouhأشرف حكيمي,"RB, RM",89,90,111000000,...,82,85,79,10,8,14,6,8,NaN,2025-2026
4,224232,26,4,2025-09-19,N. Barella,Nicolò Barella,CM,87,87,79500000,...,80,85,80,11,5,13,14,11,NaN,2025-2026

,player_id,version,name,full_name,height_cm,weight_kg,dob,positions,overall_rating,potential,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,play_styles,season
0,231866,2025-06-03,Rodri -,Rodrigo Hernández Cascante,190,82,1996-06-22,"CDM,CM",91,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-2025
1,209331,2025-06-03,Mohamed Salah Hamed Ghaly -,Mohamed Salah Hamed Ghalyمحمد صلاح,175,72,1992-06-15,"RM,RW",91,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-2025
2,252371,2025-06-03,Jude Victor William Bellingham -,Jude Victor William Bellingham,186,75,2003-06-29,"CAM,CM",90,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-2025
3,239085,2025-06-03,Erling Braut Håland -,Erling Braut Håland,195,94,2000-07-21,ST,90,92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-2025
4,238794,2025-06-03,Vini Jr. -,Vinicius José Paixão de Oliveira Junior,176,73,2000-07-12,"LW,ST",90,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-2025

,player_id,version,name,full_name,height_cm,weight_kg,dob,positions,overall_rating,potential,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,play_styles,season
0,239085,240033,Erling Haaland,Erling Braut Haaland,195,94,2000-07-21,ST,91,94,...,38,47,29,7,14,13,11,7.0,"Acrobatic +,Power Header,Quick Step",2023-2024
1,231747,240033,Kylian Mbappé,Kylian Mbappé Lottin,182,75,1998-12-20,"ST,LW",91,94,...,26,34,32,13,5,7,11,6.0,"Quick Step +,Finesse Shot,Rapid,Flair,Trivela,...",2023-2024
2,192985,240033,Kevin De Bruyne,Kevin De Bruyne,181,75,1991-06-28,"CM,CAM",91,91,...,66,70,53,15,13,5,10,13.0,"Incisive Pass +,Dead Ball,Pinged Pass,Long Bal...",2023-2024
3,231866,240033,Rodri,Rodrigo Hernández Cascante,191,82,1996-06-22,"CDM,CM",90,91,...,92,87,78,10,10,7,14,8.0,"Power Shot +,Long Ball Pass,Bruiser,Aerial",2023-2024
4,202126,240033,Harry Kane,Harry Kane,188,85,1993-07-28,ST,90,90,...,46,46,38,8,10,11,14,11.0,"Incisive Pass +,Long Ball Pass,First Touch,Tri...",2023-2024

,player_id,fifa_version,fifa_update,fifa_update_date,name,full_name,positions,overall_rating,potential,value,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,gk_speed,season
0,158023,23,9,2023-01-13,L. Messi,Lionel Andrés Messi Cuccittini,RW,91,91,54000000.0,...,20,35,24,6,11,15,14,8,NaN,2022-2023
1,165153,23,9,2023-01-13,K. Benzema,Karim Benzema,"CF, ST",91,91,64000000.0,...,43,24,18,13,11,5,5,7,NaN,2022-2023
2,188545,23,9,2023-01-13,R. Lewandowski,Robert Lewandowski,ST,91,91,84000000.0,...,35,42,19,15,6,12,8,10,NaN,2022-2023
3,192985,23,9,2023-01-13,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,107500000.0,...,65,65,53,15,13,5,10,13,NaN,2022-2023
4,231747,23,9,2023-01-13,K. Mbappé,Kylian Mbappé Lottin,"ST, LW",91,95,190500000.0,...,26,34,32,13,5,7,11,6,NaN,2022-2023

,player_id,name,full_name,positions,overall_rating,potential,value,wage,age,dob,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,gk_speed,season
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,1987-06-24,...,20,35,24,6,11,15,14,8,NaN,2021-2022
1,188545,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,1988-08-21,...,35,42,19,15,6,12,8,10,NaN,2021-2022
2,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,1985-02-05,...,24,32,24,7,11,15,14,11,NaN,2021-2022
3,190871,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,1992-02-05,...,35,32,29,9,9,15,15,11,NaN,2021-2022
4,192985,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,1991-06-28,...,68,65,53,15,13,5,10,13,NaN,2021-2022

,player_id,name,full_name,positions,overall_rating,potential,value,wage,age,dob,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,gk_speed,season
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,103500000.0,560000.0,33,1987-06-24,...,32,35,24,6,11,15,14,8,NaN,2020-2021
1,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",92,92,63000000.0,220000.0,35,1985-02-05,...,28,32,24,7,11,15,14,11,NaN,2020-2021
2,188545,R. Lewandowski,Robert Lewandowski,ST,91,91,111000000.0,240000.0,31,1988-08-21,...,35,42,19,15,6,12,8,10,NaN,2020-2021
3,190871,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,132000000.0,270000.0,28,1992-02-05,...,35,30,29,9,9,15,15,11,NaN,2020-2021
4,192985,K. De Bruyne,Kevin De Bruyne,"CAM, CM",91,91,129000000.0,370000.0,29,1991-06-28,...,68,65,53,15,13,5,10,13,NaN,2020-2021

,player_id,name,full_name,positions,overall_rating,potential,value,wage,age,dob,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,gk_speed,season
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,"RW, CF, ST",94,94,95500000.0,560000.0,32,1987-06-24,...,33,37,26,6,11,15,14,8,NaN,2019-2020
1,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",93,93,58500000.0,410000.0,34,1985-02-05,...,28,32,24,7,11,15,14,11,NaN,2019-2020
2,190871,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",92,92,105500000.0,290000.0,27,1992-02-05,...,27,26,29,9,9,15,15,11,NaN,2019-2020
3,183277,E. Hazard,Eden Hazard,"LW, CF",91,91,90000000.0,470000.0,28,1991-01-07,...,34,27,22,11,12,6,8,8,NaN,2019-2020
4,192985,K. De Bruyne,Kevin De Bruyne,"CAM, CM",91,91,90000000.0,370000.0,28,1991-06-28,...,68,58,51,15,13,5,10,13,NaN,2019-2020

In [7]:
def build_master_dataset(df_list):
    """
    Executes the inner join stack, removes duplicates, and generates 
    a diagnostic report of dropped columns per season.
    """
    season_labels = [
        '2025-2026', '2024-2025', '2023-2024', 
        '2022-2023', '2021-2022', '2020-2021', '2019-2020'
    ]
    
    # Store the original column sets before the inner join destroys them
    original_cols = [set(df.columns) for df in df_list]
    
    # Step 2: Inner Join Concatenation
    print("Executing Outer Join...")
    master_df = pd.concat(df_list, join='outer', ignore_index=True)
    master_col_set = set(master_df.columns)
    
    # Generate Drop Report via Set Difference
    print("\n--- Column Drop Diagnostic Report ---")
    for i, orig_set in enumerate(original_cols):
        dropped_cols = orig_set - master_col_set
        if dropped_cols:
            print(f"Season {season_labels[i]} dropped {len(dropped_cols)} columns:")
            # Sorting for readability in the terminal
            print(f" -> {sorted(list(dropped_cols))}\n")
        else:
            print(f"Season {season_labels[i]} dropped 0 columns.\n")
            
    # Step 3: Anomaly Resolution
    rows_before = len(master_df)
    master_df.drop_duplicates(subset=['player_id', 'season'], keep='first', inplace=True)
    rows_after = len(master_df)
    
    # Step 4: Index Reset
    master_df.reset_index(drop=True, inplace=True)
    
    # Final Output Summary
    print("--- Final Pipeline Stats ---")
    print(f"Rows dropped during deduplication (22/23 anomaly): {rows_before - rows_after}")
    print(f"Final Master Dataset Shape: {master_df.shape}")
    print(f"Uniform Features Available: {len(master_df.columns)}")
    
    return master_df

In [8]:
# Execution:
master_df = build_master_dataset(df_list)

Executing Outer Join...

--- Column Drop Diagnostic Report ---
Season 2025-2026 dropped 0 columns.

Season 2024-2025 dropped 0 columns.

Season 2023-2024 dropped 0 columns.

Season 2022-2023 dropped 0 columns.

Season 2021-2022 dropped 0 columns.

Season 2020-2021 dropped 0 columns.

Season 2019-2020 dropped 0 columns.

--- Final Pipeline Stats ---
Rows dropped during deduplication (22/23 anomaly): 146112
Final Master Dataset Shape: (132169, 91)
Uniform Features Available: 91

In [10]:
# 1. Verify the shape of the 22/23 season data inside the master dataframe
shape_22_23 = master_df[master_df['season'] == '2022-2023'].shape
print(f"Verified 2022/23 Season Shape: {shape_22_23}")

# 2. Export the final unified dataset to a CSV file
export_filename = 'data/sofifa/newdata/players/CLEANED/SOFIFA_PLAYERS.csv'
master_df.to_csv(export_filename, index=False)
print(f"Export complete. File saved as: {export_filename}")

Verified 2022/23 Season Shape: (20621, 91)
Export complete. File saved as: data/sofifa/newdata/players/CLEANED/SOFIFA_PLAYERS.csv

# player matching

In [1]:
import os
import unicodedata
import pandas as pd

SSWY_INPUT_PATH = "data/unified_tables/players/matched/final_combined_players.csv"
SOFIFA_INPUT_PATH = "data/sofifa/newdata/players/CLEANED/SOFIFA_PLAYERS.csv"

# =============================================================================
# COUNTRY ALIAS DICTIONARY
# =============================================================================
COUNTRY_MAP = {
    "england": "united kingdom",
    "scotland": "united kingdom",
    "wales": "united kingdom",
    "northern ireland": "united kingdom",
    "usa": "united states",
    "korea republic": "south korea",
    "korea, republic of": "south korea",
    "republic of ireland": "ireland",
    "china pr": "china",
    "turkiye": "turkey",
    "cote d'ivoire": "ivory coast",
    "dr congo": "congo dr",
    "congo pr": "congo",
    "czechia": "czech republic",
    "bosnia herzegovina": "bosnia and herzegovina",
    "ir iran": "iran",
    "cape verde islands": "cape verde",
    "st kitts & nevis": "saint kitts and nevis",
    "antigua & barbuda": "antigua and barbuda",
    "trinidad & tobago": "trinidad and tobago",
}

In [2]:
def normalize_string_series(series: pd.Series) -> pd.Series:
    """Vectorized string cleaning: strips diacritics, converts to lowercase,removes punctuation/trailing white spaces, and handles nulls safely.
    """
    # Fill missing values and cast to string
    clean_series = series.fillna("").astype(str)

    # Decompose unicode characters (e.g., é -> e + ´)
    clean_series = clean_series.apply(
        lambda x: unicodedata.normalize("NFD", x)
    )

    # Encode to ASCII (dropping the dangling accents), then decode back
    clean_series = clean_series.apply(
        lambda x: x.encode("ascii", "ignore").decode("utf-8")
    )

    # Lowercase, clean punctuation artifacts, and strip white spaces
    clean_series = (
        clean_series.str.lower()
        .str.replace(r"[^\w\s]", "", regex=True)
        .str.strip()
    )

    return clean_series

In [3]:
print("LAUNCHING PHASE 1: PRE-FLIGHT STANDARDIZATION")
# print("=" * 60)

if not os.path.exists(SSWY_INPUT_PATH) or not os.path.exists(SOFIFA_INPUT_PATH):
    print("ERROR: Input file paths are incorrect. Please update Cell 1.")
else:
    # 1. Loading
    print("Loading datasets into memory...")
    df_sswy = pd.read_csv(SSWY_INPUT_PATH)
    df_sofifa = pd.read_csv(SOFIFA_INPUT_PATH)

    # 2. Namespace Protection
    print("Applying 'sofifa_' prefix to columns...")
    df_sofifa = df_sofifa.add_prefix("sofifa_")
    print("Enforcing ID string types to prevent rolling dictionary failures...")
    
    # #UPDATE: Force SSWY IDs to string and strip float artifacts
    df_sswy['soccersolver_id'] = df_sswy['soccersolver_id'].astype(str).str.replace(r'\.0$', '', regex=True)
    # #UPDATE: Force Sofifa IDs to string and strip float artifacts
    df_sofifa['sofifa_player_id'] = df_sofifa['sofifa_player_id'].astype(str).str.replace(r'\.0$', '', regex=True)

    # 3. Deduplication (Sofifa Version Control)
    print("Isolating definitive seasonal roster updates...")
    df_sofifa["sofifa_fifa_update_date"] = pd.to_datetime(df_sofifa["sofifa_fifa_update_date"])
    df_sofifa = df_sofifa.sort_values(by="sofifa_fifa_update_date", ascending=True)
    
    initial_sofifa_count = len(df_sofifa)
    df_sofifa = df_sofifa.drop_duplicates(subset=["sofifa_player_id", "sofifa_season"], keep="last")
    print(f" -> Removed {initial_sofifa_count - len(df_sofifa)} transient roster updates.")

    # 4. Text Normalization & Mapping
    print("Normalizing names and standardizing country aliases...")
    df_sswy["normalized_name"] = normalize_string_series(df_sswy["name"])
    df_sofifa["normalized_name"] = normalize_string_series(df_sofifa["sofifa_full_name"])

    # Extract, lowercase, map, and clean nationalities
    raw_sswy_nat = df_sswy["nationality"].fillna("").astype(str).str.lower().str.strip()
    raw_sofifa_nat = df_sofifa["sofifa_country_name"].fillna("").astype(str).str.lower().str.strip()

    df_sswy["normalized_nationality"] = normalize_string_series(
        raw_sswy_nat.map(lambda x: COUNTRY_MAP.get(x, x))
    )
    df_sofifa["normalized_nationality"] = normalize_string_series(
        raw_sofifa_nat.map(lambda x: COUNTRY_MAP.get(x, x))
    )

    # 5. Temporal Alignment & Block Extraction
    print("Aligning temporal data and extracting evaluation blocks...")
    df_sswy["birth_date"] = pd.to_datetime(df_sswy["birth_date"], errors="coerce")
    df_sofifa["sofifa_dob"] = pd.to_datetime(df_sofifa["sofifa_dob"], errors="coerce")

    df_sswy["clean_dob"] = df_sswy["birth_date"].dt.strftime("%Y-%m-%d")
    df_sofifa["clean_dob"] = df_sofifa["sofifa_dob"].dt.strftime("%Y-%m-%d")

    df_sswy["Birth_Year"] = df_sswy["birth_date"].dt.year.fillna(0).astype(int)
    df_sofifa["Birth_Year"] = df_sofifa["sofifa_dob"].dt.year.fillna(0).astype(int)

    df_sswy["name_first_letter"] = df_sswy["normalized_name"].str[0].fillna("")
    df_sofifa["name_first_letter"] = df_sofifa["normalized_name"].str[0].fillna("")

    # print("-" * 60)
    print("PHASE 1 COMPLETE")
    print(f"Final Counts -> SSWY: {len(df_sswy)} rows | Sofifa: {len(df_sofifa)} rows")
    print("DataFrames are currently held in memory. Ready for Phase 2.")
    # print("=" * 60)

LAUNCHING PHASE 1: PRE-FLIGHT STANDARDIZATION
Loading datasets into memory...

C:\Users\ashwy\AppData\Local\Temp\ipykernel_38524\2835120639.py:10: DtypeWarning: Columns (0: fifa_update_date, 1: value, 2: wage, 3: club_loaned_from, 4: club_contract_valid_until, 5: nation_position, 6: weak_foot, 7: moves, 8: international_reputation, 9: work_rate, 10: release_clause, 11: play_styles, 12: agility, 13: balance, 14: gk_positioning, 15: version, 16: club_logo, 17: country_league_id, 18: country_league_name, 19: country_flag, 20: country_position) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sofifa = pd.read_csv(SOFIFA_INPUT_PATH)

Applying 'sofifa_' prefix to columns...
Enforcing ID string types to prevent rolling dictionary failures...
Isolating definitive seasonal roster updates...
 -> Removed 0 transient roster updates.
Normalizing names and standardizing country aliases...
Aligning temporal data and extracting evaluation blocks...
PHASE 1 COMPLETE
Final Counts -> SSWY: 382339 rows | Sofifa: 132169 rows
DataFrames are currently held in memory. Ready for Phase 2.

In [4]:
display(df_sofifa.head(10))
display(df_sswy.head(10))

,sofifa_player_id,sofifa_fifa_version,sofifa_fifa_update,sofifa_fifa_update_date,sofifa_name,sofifa_full_name,sofifa_positions,sofifa_overall_rating,sofifa_potential,sofifa_value,...,sofifa_country_league_id,sofifa_country_league_name,sofifa_country_flag,sofifa_country_rating,sofifa_country_position,normalized_name,normalized_nationality,clean_dob,Birth_Year,name_first_letter
75502,262759,23.0,1.0,2022-09-01,S. Black,Stephen Black,CB,47,61,110000.0,...,NaN,NaN,NaN,NaN,NaN,stephen black,ireland,2002-03-01,2002,s
75026,251558,23.0,1.0,2022-09-01,L. Daneels,Lennerd Daneels,"LW, RW, ST",64,69,875000.0,...,NaN,NaN,NaN,NaN,NaN,lennerd daneels,belgium,1998-04-10,1998,l
75025,248588,23.0,1.0,2022-09-01,C. Itu,Cătălin Mihai Itu,CM,64,72,1300000.0,...,NaN,NaN,NaN,NaN,NaN,catalin mihai itu,romania,1999-10-26,1999,c
75024,247135,23.0,1.0,2022-09-01,A. Hristov,Andrea Hristov,CB,64,74,1200000.0,...,NaN,NaN,NaN,NaN,NaN,andrea hristov,bulgaria,1999-03-01,1999,a
75023,246861,23.0,1.0,2022-09-01,A. Riccardi,Alessio Riccardi,"CM, CAM",64,77,1400000.0,...,NaN,NaN,NaN,NaN,NaN,alessio riccardi,italy,2001-04-03,2001,a
75022,246039,23.0,1.0,2022-09-01,Jorge Mier,Jorge Mier Martínez,"RB, LB",64,71,1100000.0,...,NaN,NaN,NaN,NaN,NaN,jorge mier martinez,spain,1999-02-04,1999,j
75021,241128,23.0,1.0,2022-09-01,J. Mejías,Josua Antonio Mejías García,"CB, RB",64,71,1100000.0,...,NaN,NaN,NaN,NaN,NaN,josua antonio mejias garcia,venezuela,1998-06-09,1998,j
75020,237495,23.0,1.0,2022-09-01,A. Ferrante,Jonathan Alexis Ferrante,"ST, CF",64,64,625000.0,...,NaN,NaN,NaN,NaN,NaN,jonathan alexis ferrante,italy,1995-06-27,1995,j
75019,233878,23.0,1.0,2022-09-01,R. Moise,Romario Florin Moise,"CM, CAM, RM",64,66,725000.0,...,NaN,NaN,NaN,NaN,NaN,romario florin moise,romania,1995-09-21,1995,r
75027,252082,23.0,1.0,2022-09-01,C. Brym,Charles-Andreas Brym,"ST, RM",64,71,1200000.0,...,NaN,NaN,NaN,NaN,NaN,charlesandreas brym,canada,1998-08-08,1998,c

,soccersolver_id,name,team,team_id,position_ss,main_position,age,birth_date,nationality,height,...,weight_kg,foot,position_wy,role_code,status,normalized_name,normalized_nationality,clean_dob,Birth_Year,name_first_letter
0,205465,Marc-Aurèle Caillard,EA Guingamp,855,GK,Goalkeeper,25.0,1994-05-12,France,192,...,79.0,right,Goalkeeper,GKP,active,marcaurele caillard,france,1994-05-12,1994,m
1,358505,Théo Guivarch,EA Guingamp,855,GK,Goalkeeper,23.0,1995-11-17,France,195,...,87.0,right,Goalkeeper,GKP,active,theo guivarch,france,1995-11-17,1995,t
2,296359,Félix Eboa Eboa,EA Guingamp,855,DEF,Centre-Back,22.0,1997-04-19,Cameroon,186,...,80.0,right,Defender,DEF,active,felix eboa eboa,cameroon,1997-04-19,1997,f
3,413118,Sikou Niakaté,EA Guingamp,855,DEF,Centre-Back,19.0,1999-07-10,Mali,186,...,80.0,left,Defender,DEF,active,sikou niakate,mali,1999-07-10,1999,s
4,468895,Yohan Baret,EA Guingamp,855,DEF,Centre-Back,18.0,2001-05-16,France,184,...,76.0,right,Defender,DEF,active,yohan baret,france,2001-05-16,2001,y
5,56820,Jérémy Sorbon,EA Guingamp,855,DEF,Centre-Back,35.0,1983-08-05,France,183,...,79.0,right,Defender,DEF,retired,jeremy sorbon,france,1983-08-05,1983,j
6,796895,Baptiste Roux,EA Guingamp,855,DEF,Centre-Back,19.0,1999-11-26,France,190,...,79.0,left,Defender,DEF,active,baptiste roux,france,1999-11-26,1999,b
7,197860,Pedro Rebocho,EA Guingamp,855,DEF,Left-Back,24.0,1995-01-23,Portugal,171,...,66.0,left,Defender,DEF,active,pedro rebocho,portugal,1995-01-23,1995,p
8,272640,Morgan Poaty,EA Guingamp,855,DEF,Left-Back,21.0,1997-07-15,Congo,177,...,75.0,left,Defender,DEF,active,morgan poaty,congo,1997-07-15,1997,m
9,127177,Gaëtan Bussmann,EA Guingamp,855,DEF,Left-Back,28.0,1991-02-02,France,184,...,80.0,left,Defender,DEF,active,gaetan bussmann,france,1991-02-02,1991,g

In [5]:
from thefuzz import fuzz
import pandas as pd
import numpy as np

def calculate_match_score(row) -> pd.Series:
    """
    Executes the 100-point scoring matrix. Thresholds: >= 80 (Matched), 72-79.9 (Partial), < 72 (Discard)
    """
    score = 0.0
    
    # 1. Name Match (60 Points) - using token_set_ratio for subset neutralization
    name_sswy = str(row.get('normalized_name_sswy', ''))
    name_sof = str(row.get('normalized_name_sof', ''))
    
    if name_sswy and name_sof:
        score += fuzz.token_set_ratio(name_sswy, name_sof) * 0.60

    # 2. Nationality Match (25 Points)
    nat_sswy = str(row.get('normalized_nationality_sswy', 'nan'))
    nat_sof = str(row.get('normalized_nationality_sof', 'nan'))
    if nat_sswy != 'nan' and nat_sof != 'nan' and nat_sswy == nat_sof:
        score += 25.0

    # 3. Height Match (7.5 Points)
    h_sswy = row.get('height_cm')
    h_sof = row.get('sofifa_height_cm')
    if pd.notna(h_sswy) and pd.notna(h_sof):
        if abs(float(h_sswy) - float(h_sof)) <= 3.0:
            score += 7.5

    # 4. Preferred Foot (7.5 Points)
    foot_sswy = str(row.get('foot', 'nan')).lower()
    foot_sof = str(row.get('sofifa_preferred_foot', 'nan')).lower()
    if foot_sswy != 'nan' and foot_sof != 'nan' and foot_sswy == foot_sof:
        score += 7.5

    # Determine Routing Status
    if score >= 80.0:
        status = 'MATCHED'
    elif score >= 72.0:
        status = 'PARTIAL'
    else:
        status = 'DISCARD'
        
    return pd.Series([score, status], index=['match_score', 'match_status'])

In [6]:
print("LAUNCHING PHASE 2: SNOWBALL IDENTITY RESOLUTION ENGINE")
# print("=" * 80)

final_matched_dfs = []
final_partial_dfs = []
final_unmatched_sswy_dfs = []
final_unmatched_sofifa_dfs = []

# Initialize the empty Rolling Dictionary
rolling_id_dictionary = pd.DataFrame(columns=['soccersolver_id', 'sofifa_player_id'])

# Sort seasons chronologically to ensure the snowball effect works
seasons = sorted(df_sswy['season'].dropna().unique())
total_seasons = len(seasons)

for idx, season in enumerate(seasons, 1):
    print(f"\n[{idx}/{total_seasons}] LIVE TRACKER: Season {season}")
    print("-" * 80)
    
    curr_sswy = df_sswy[df_sswy['season'] == season].copy()
    curr_sof = df_sofifa[df_sofifa['sofifa_season'] == season].copy()
    
    initial_sswy = len(curr_sswy)
    initial_sof = len(curr_sof)
    
    season_matched = 0
    season_partial = 0
    
    # -------------------------------------------------------------------------
    # PASS 0: The VIP Bypass (Rolling Dictionary)
    # -------------------------------------------------------------------------
    p0_matched_count = 0
    if not rolling_id_dictionary.empty:
        valid_map = rolling_id_dictionary[
            rolling_id_dictionary['soccersolver_id'].isin(curr_sswy['soccersolver_id']) & 
            rolling_id_dictionary['sofifa_player_id'].isin(curr_sof['sofifa_player_id'])
        ]
        
        if not valid_map.empty:
            p0_sswy = curr_sswy[curr_sswy['soccersolver_id'].isin(valid_map['soccersolver_id'])].copy()
            p0_sof = curr_sof[curr_sof['sofifa_player_id'].isin(valid_map['sofifa_player_id'])].copy()
            
            p0_matched = p0_sswy.merge(valid_map, on='soccersolver_id').merge(p0_sof, on='sofifa_player_id', suffixes=('_sswy', '_sof'))
            p0_matched['match_score'] = 100.0
            p0_matched['match_status'] = 'MATCHED'
            
            p0_matched = p0_matched.drop_duplicates(subset=['sofifa_player_id'], keep='first')
            p0_matched = p0_matched.drop_duplicates(subset=['soccersolver_id'], keep='first')
            
            p0_matched_count = len(p0_matched)
            season_matched += p0_matched_count
            final_matched_dfs.append(p0_matched)
            
            # Remove bypassed players from the working pool
            curr_sswy = curr_sswy[~curr_sswy['soccersolver_id'].isin(valid_map['soccersolver_id'])]
            curr_sof = curr_sof[~curr_sof['sofifa_player_id'].isin(valid_map['sofifa_player_id'])]
            
    print(f"  -> Pass 0 (ID Bypass):      {p0_matched_count} Matched (Current Dictionary Size: {len(rolling_id_dictionary)})")
    print(f"     [Rookies/Leftovers pushed to Heuristics: {len(curr_sof)} Sofifa Players]")

    # -------------------------------------------------------------------------
    # PASS 1: The Exact Anchor (Date of Birth)
    # -------------------------------------------------------------------------
    p1_merge = curr_sswy.merge(curr_sof, on='clean_dob', how='inner', suffixes=('_sswy', '_sof'))
    
    p1_matched_count = p1_partial_count = 0
    p1_matched = pd.DataFrame()
    if not p1_merge.empty:
        p1_merge[['match_score', 'match_status']] = p1_merge.apply(calculate_match_score, axis=1)
        
        p1_merge = p1_merge.sort_values('match_score', ascending=False)
        p1_merge = p1_merge.drop_duplicates(subset=['sofifa_player_id'], keep='first')
        p1_merge = p1_merge.drop_duplicates(subset=['soccersolver_id'], keep='first')
        
        p1_matched = p1_merge[p1_merge['match_status'] == 'MATCHED']
        p1_partial = p1_merge[p1_merge['match_status'] == 'PARTIAL']
        
        p1_matched_count = len(p1_matched)
        p1_partial_count = len(p1_partial)
        season_matched += p1_matched_count
        season_partial += p1_partial_count
        
        final_matched_dfs.append(p1_matched)
        final_partial_dfs.append(p1_partial)
        
        routed_sswy_ids = pd.concat([p1_matched['soccersolver_id'], p1_partial['soccersolver_id']])
        routed_sof_ids = pd.concat([p1_matched['sofifa_player_id'], p1_partial['sofifa_player_id']])
        
        curr_sswy = curr_sswy[~curr_sswy['soccersolver_id'].isin(routed_sswy_ids)]
        curr_sof = curr_sof[~curr_sof['sofifa_player_id'].isin(routed_sof_ids)]
        
    print(f"  -> Pass 1 (Exact DOB):      {p1_matched_count} Matched | {p1_partial_count} Partial")

    # -------------------------------------------------------------------------
    # PASS 2: The Nationality Net (Birth Year + Nationality)
    # -------------------------------------------------------------------------
    p2_merge = curr_sswy.merge(curr_sof, on=['Birth_Year', 'normalized_nationality'], how='inner', suffixes=('_sswy', '_sof'))
    
    p2_matched_count = p2_partial_count = 0
    p2_matched = pd.DataFrame()
    if not p2_merge.empty:
        p2_merge['normalized_nationality_sswy'] = p2_merge['normalized_nationality']
        p2_merge['normalized_nationality_sof'] = p2_merge['normalized_nationality']
        
        p2_merge[['match_score', 'match_status']] = p2_merge.apply(calculate_match_score, axis=1)
        
        p2_merge = p2_merge.sort_values('match_score', ascending=False)
        p2_merge = p2_merge.drop_duplicates(subset=['sofifa_player_id'], keep='first')
        p2_merge = p2_merge.drop_duplicates(subset=['soccersolver_id'], keep='first')
        
        p2_matched = p2_merge[p2_merge['match_status'] == 'MATCHED']
        p2_partial = p2_merge[p2_merge['match_status'] == 'PARTIAL']
        
        p2_matched_count = len(p2_matched)
        p2_partial_count = len(p2_partial)
        season_matched += p2_matched_count
        season_partial += p2_partial_count
        
        final_matched_dfs.append(p2_matched)
        final_partial_dfs.append(p2_partial)
        
        routed_sswy_ids = pd.concat([p2_matched['soccersolver_id'], p2_partial['soccersolver_id']])
        routed_sof_ids = pd.concat([p2_matched['sofifa_player_id'], p2_partial['sofifa_player_id']])
        
        curr_sswy = curr_sswy[~curr_sswy['soccersolver_id'].isin(routed_sswy_ids)]
        curr_sof = curr_sof[~curr_sof['sofifa_player_id'].isin(routed_sof_ids)]
        
    print(f"  -> Pass 2 (Nationality):    {p2_matched_count} Matched | {p2_partial_count} Partial")

    # -------------------------------------------------------------------------
    # PASS 3: The Dual-National Safety Net (Birth Year + First Letter)
    # -------------------------------------------------------------------------
    p3_merge = curr_sswy.merge(curr_sof, on=['Birth_Year', 'name_first_letter'], how='inner', suffixes=('_sswy', '_sof'))
    
    p3_matched_count = p3_partial_count = 0
    if not p3_merge.empty:
        p3_merge[['match_score', 'match_status']] = p3_merge.apply(calculate_match_score, axis=1)
        
        p3_merge = p3_merge.sort_values('match_score', ascending=False)
        p3_merge = p3_merge.drop_duplicates(subset=['sofifa_player_id'], keep='first')
        p3_merge = p3_merge.drop_duplicates(subset=['soccersolver_id'], keep='first')
        
        # GUARDRAIL: Ban Pass 3 from Matched (Forces manual review)
        p3_merge.loc[p3_merge['match_status'] == 'MATCHED', 'match_status'] = 'PARTIAL'
        p3_partial = p3_merge[p3_merge['match_status'] == 'PARTIAL']
        
        p3_partial_count = len(p3_partial)
        season_partial += p3_partial_count
        final_partial_dfs.append(p3_partial)
        
        routed_sswy_ids = p3_partial['soccersolver_id']
        routed_sof_ids = p3_partial['sofifa_player_id']
        
        curr_sswy = curr_sswy[~curr_sswy['soccersolver_id'].isin(routed_sswy_ids)]
        curr_sof = curr_sof[~curr_sof['sofifa_player_id'].isin(routed_sof_ids)]
        
    print(f"  -> Pass 3 (Safety Net):     0 Matched (Safeguard) | {p3_partial_count} Partial")
    
    # -------------------------------------------------------------------------
    # DICTIONARY UPDATE
    # -------------------------------------------------------------------------
    # Append strictly the PERFECT MATCHES from Pass 1 and Pass 2 to the dictionary
    new_perfect_ids = []
    if not p1_matched.empty:
        new_perfect_ids.append(p1_matched[['soccersolver_id', 'sofifa_player_id']])
    if not p2_matched.empty:
        new_perfect_ids.append(p2_matched[['soccersolver_id', 'sofifa_player_id']])
        
    if new_perfect_ids:
        new_pairs_df = pd.concat(new_perfect_ids, ignore_index=True)
        rolling_id_dictionary = pd.concat([rolling_id_dictionary, new_pairs_df], ignore_index=True)
        rolling_id_dictionary = rolling_id_dictionary.drop_duplicates()
        print(f"  [+] Added {len(new_pairs_df)} newly discovered pairs to the Rolling Dictionary.")

    # UNMATCHED ISOLATION
    final_unmatched_sswy_dfs.append(curr_sswy)
    final_unmatched_sofifa_dfs.append(curr_sof)

print("\n" + "=" * 80)
print("SNOWBALL LOOP COMPLETE. EXECUTING RETROACTIVE LOOP-BACK...")
print("=" * 80)

# Concatenate all lists
df_master_matched = pd.concat(final_matched_dfs, ignore_index=True) if final_matched_dfs else pd.DataFrame()
df_master_partial = pd.concat(final_partial_dfs, ignore_index=True) if final_partial_dfs else pd.DataFrame()
df_unmatched_sswy = pd.concat(final_unmatched_sswy_dfs, ignore_index=True) if final_unmatched_sswy_dfs else pd.DataFrame()
df_unmatched_sofifa = pd.concat(final_unmatched_sofifa_dfs, ignore_index=True) if final_unmatched_sofifa_dfs else pd.DataFrame()

initial_unmatched_sswy = len(df_unmatched_sswy)

# Retroactive Rescue: Join Unmatched Data against the final matured dictionary
if not df_unmatched_sswy.empty and not df_unmatched_sofifa.empty and not rolling_id_dictionary.empty:
    
    # We must ensure we rescue records from the same season
    rescued_records = df_unmatched_sswy.merge(
        rolling_id_dictionary, on='soccersolver_id', how='inner'
    ).merge(
        df_unmatched_sofifa, left_on=['sofifa_player_id', 'season'], right_on=['sofifa_player_id', 'sofifa_season'], suffixes=('_sswy', '_sof')
    )
    
    rescued_records['match_score'] = 100.0
    rescued_records['match_status'] = 'MATCHED (RESCUED)'
    
    rescued_count = len(rescued_records)
    
    if rescued_count > 0:
        # Append rescued records to master matched
        df_master_matched = pd.concat([df_master_matched, rescued_records], ignore_index=True)
        
        # Drop rescued records from unmatched pools
        df_unmatched_sswy = df_unmatched_sswy[~df_unmatched_sswy['soccersolver_id'].isin(rescued_records['soccersolver_id'])]
        df_unmatched_sofifa = df_unmatched_sofifa[~df_unmatched_sofifa['sofifa_player_id'].isin(rescued_records['sofifa_player_id'])]
        
        print(f"Retroactive Rescue Successful: Salvaged {rescued_count} orphaned records from early seasons.")
    else:
        print("Retroactive Rescue: 0 orphans found matching the final dictionary.")

print(f"\nFinal Global Statistics:")
print(f"  - Total Matched: {len(df_master_matched)}")
print(f"  - Total Partial (Review): {len(df_master_partial)}")
print(f"  - Total Unmatched SSWY: {len(df_unmatched_sswy)}")
print(f"  - Total Unmatched Sofifa: {len(df_unmatched_sofifa)}")

LAUNCHING PHASE 2: SNOWBALL IDENTITY RESOLUTION ENGINE

[1/7] LIVE TRACKER: Season 2019-2020
--------------------------------------------------------------------------------
  -> Pass 0 (ID Bypass):      0 Matched (Current Dictionary Size: 0)
     [Rookies/Leftovers pushed to Heuristics: 18483 Sofifa Players]
  -> Pass 1 (Exact DOB):      11827 Matched | 776 Partial
  -> Pass 2 (Nationality):    457 Matched | 379 Partial
  -> Pass 3 (Safety Net):     0 Matched (Safeguard) | 30 Partial
  [+] Added 12284 newly discovered pairs to the Rolling Dictionary.

[2/7] LIVE TRACKER: Season 2020-2021
--------------------------------------------------------------------------------
  -> Pass 0 (ID Bypass):      8977 Matched (Current Dictionary Size: 12284)
     [Rookies/Leftovers pushed to Heuristics: 9967 Sofifa Players]
  -> Pass 1 (Exact DOB):      3131 Matched | 743 Partial
  -> Pass 2 (Nationality):    239 Matched | 405 Partial
  -> Pass 3 (Safety Net):     0 Matched (Safeguard) | 27 Partial
  [+] Added 3370 newly discovered pairs to the Rolling Dictionary.

[3/7] LIVE TRACKER: Season 2021-2022
--------------------------------------------------------------------------------
  -> Pass 0 (ID Bypass):      9577 Matched (Current Dictionary Size: 15654)
     [Rookies/Leftovers pushed to Heuristics: 9660 Sofifa Players]
  -> Pass 1 (Exact DOB):      2859 Matched | 756 Partial
  -> Pass 2 (Nationality):    236 Matched | 402 Partial
  -> Pass 3 (Safety Net):     0 Matched (Safeguard) | 30 Partial
  [+] Added 3095 newly discovered pairs to the Rolling Dictionary.

[4/7] LIVE TRACKER: Season 2022-2023
--------------------------------------------------------------------------------
  -> Pass 0 (ID Bypass):      10445 Matched (Current Dictionary Size: 18749)
     [Rookies/Leftovers pushed to Heuristics: 10164 Sofifa Players]
  -> Pass 1 (Exact DOB):      3133 Matched | 705 Partial
  -> Pass 2 (Nationality):    237 Matched | 461 Partial
  -> Pass 3 (Safety Net):     0 Matched (Safeguard) | 35 Partial
  [+] Added 3370 newly discovered pairs to the Rolling Dictionary.

[5/7] LIVE TRACKER: Season 2023-2024
--------------------------------------------------------------------------------
  -> Pass 0 (ID Bypass):      10090 Matched (Current Dictionary Size: 22119)
     [Rookies/Leftovers pushed to Heuristics: 8213 Sofifa Players]
  -> Pass 1 (Exact DOB):      17 Matched | 2541 Partial
  -> Pass 2 (Nationality):    12 Matched | 41 Partial
  -> Pass 3 (Safety Net):     0 Matched (Safeguard) | 70 Partial
  [+] Added 29 newly discovered pairs to the Rolling Dictionary.

[6/7] LIVE TRACKER: Season 2024-2025
--------------------------------------------------------------------------------
  -> Pass 0 (ID Bypass):      8943 Matched (Current Dictionary Size: 22148)
     [Rookies/Leftovers pushed to Heuristics: 9218 Sofifa Players]
  -> Pass 1 (Exact DOB):      34 Matched | 3216 Partial
  -> Pass 2 (Nationality):    9 Matched | 55 Partial
  -> Pass 3 (Safety Net):     0 Matched (Safeguard) | 75 Partial
  [+] Added 43 newly discovered pairs to the Rolling Dictionary.

[7/7] LIVE TRACKER: Season 2025-2026
--------------------------------------------------------------------------------
  -> Pass 0 (ID Bypass):      8086 Matched (Current Dictionary Size: 22191)
     [Rookies/Leftovers pushed to Heuristics: 10317 Sofifa Players]
  -> Pass 1 (Exact DOB):      4610 Matched | 470 Partial
  -> Pass 2 (Nationality):    179 Matched | 300 Partial
  -> Pass 3 (Safety Net):     0 Matched (Safeguard) | 13 Partial
  [+] Added 4789 newly discovered pairs to the Rolling Dictionary.

================================================================================
SNOWBALL LOOP COMPLETE. EXECUTING RETROACTIVE LOOP-BACK...
================================================================================
Retroactive Rescue Successful: Salvaged 2403 orphaned records from early seasons.

Final Global Statistics:
  - Total Matched: 85501
  - Total Partial (Review): 11530
  - Total Unmatched SSWY: 264704
  - Total Unmatched Sofifa: 35278

In [9]:
import pandas as pd

# Load the raw data as strings
raw_sofifa = pd.read_csv(SOFIFA_INPUT_PATH, dtype=str)

# Grab the very first row of 2022-2023 and 2023-2024
good_row = raw_sofifa[raw_sofifa['season'] == '2022-2023'].iloc[0]
bad_row = raw_sofifa[raw_sofifa['season'] == '2023-2024'].iloc[0]

# Build a side-by-side comparison matrix
comparison = pd.DataFrame({
    'Column Header': raw_sofifa.columns,
    '22/23 (Clean Format)': good_row.values,
    '23/24 (Broken Format)': bad_row.values
})

# Force Pandas to show the entire list
pd.set_option('display.max_rows', None)

print("=" * 70)
print("DIAGNOSTIC: STRUCTURAL ALIGNMENT CHECK")
print("=" * 70)
print(comparison)

======================================================================
DIAGNOSTIC: STRUCTURAL ALIGNMENT CHECK
======================================================================
                Column Header  \
0                   player_id
1                fifa_version
2                 fifa_update
3            fifa_update_date
4                        name
5                   full_name
6                   positions
7              overall_rating
8                   potential
9                       value
10                       wage
11                        age
12                        dob
13                  height_cm
14                  weight_kg
15                  league_id
16           club_league_name
17               league_level
18                    club_id
19                  club_name
20              club_position
21            club_kit_number
22           club_loaned_from
23                club_joined
24  club_contract_valid_until
25                 country_id
26               country_name
27             nation_team_id
28            nation_position
29         country_kit_number
30             preferred_foot
31                  weak_foot
32                      moves
33   international_reputation
34                  work_rate
35                  body_type
36                  real_face
37             release_clause
38               specialities
39                play_styles
40                       pace
41                   shooting
42                    passing
43            macro_dribbling
44                  defending
45                     physic
46                   crossing
47                  finishing
48           heading_accuracy
49              short_passing
50                    volleys
51                  dribbling
52                      curve
53                fk_accuracy
54               long_passing
55               ball_control
56               acceleration
57               sprint_speed
58                    agility
59                  reactions
60                    balance
61                 shot_power
62                    jumping
63                    stamina
64                   strength
65                 long_shots
66                 aggression
67              interceptions
68                positioning
69                     vision
70                  penalties
71                  composure
72        defensive_awareness
73            standing_tackle
74             sliding_tackle
75                  gk_diving
76                gk_handling
77                 gk_kicking
78             gk_positioning
79                gk_reflexes
80                   gk_speed
81                     season
82                    version
83             club_league_id
84                  club_logo
85                club_rating
86          country_league_id
87        country_league_name
88               country_flag
89             country_rating
90           country_position

                                 22/23 (Clean Format)  \
0                                              158023
1                                                23.0
2                                                 9.0
3                                          2023-01-13
4                                            L. Messi
5                      Lionel Andrés Messi Cuccittini
6                                                  RW
7                                                  91
8                                                  91
9                                          54000000.0
10                                           195000.0
11                                               35.0
12                                         1987-06-24
13                                                169
14                                                 67
15                                               16.0
16                                            Ligue 1
17                                                1.0
18                                               73.0
19                                Paris Saint Germain
20                                                 RS
21                                               30.0
22                                                NaN
23                                         2021-08-10
24                                             2023.0
25                                               52.0
26                                          Argentina
27                                             1369.0
28                                                 RW
29                                               10.0
30                                               Left
31                                                  4
32                                                  4
33                                                  5
34                                            Low/Low
35                                             Unique
36                                                Yes
37                                         99900000.0
38  #Dribbler, #Distance Shooter, #FK Specialist, ...
39  Finesse Shot, Long Shot Taker (AI), Playmaker ...
40                                               81.0
41                                               89.0
42                                               90.0
43                                               94.0
44                                               34.0
45                                               64.0
46                                               84.0
47                                               90.0
48                                               70.0
49                                               91.0
50                                               88.0
51                                               95.0
52                                               93.0
53                                               93.0
54                                               90.0
55                                               93.0
56                                               87.0
57                                               76.0
58                                                 91
59                                               92.0
60                                                 95
61                                               86.0
62                                               68.0
63                                               70.0
64                                               68.0
65                                               91.0
66                                               44.0
67                                               40.0
68                                               93.0
69                                               94.0
70                                               75.0
71                                               96.0
72                                               20.0
73                                               35.0
74                                               24.0
75                                                6.0
76                                               11.0
77                                               15.0
78                                                 14
79                                                8.0
80                                                NaN
81                                          2022-2023
82                                                NaN
83                                                NaN
84                                                NaN
85                                                NaN
86                                                NaN
87                                                NaN
88                                                NaN
89                                                NaN
90                                                NaN

                                23/24 (Broken Format)
0                                              239085
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                      Erling Haaland
5                                Erling Braut Haaland
6                                                  ST
7                                                  91
8                                                  94
9                                               €185M
10                                              €340K
11                                                NaN
12                                         2000-07-21
13                                                195
14                                                 94
15                                                NaN
16                                     Premier League
17                                                NaN
18                                               10.0
19                                    Manchester City
20                                                 ST
21                                                9.0
22                                                NaN
23                                         2022-07-01
24                                               2027
25                                             1352.0
26                                             Norway
27                                                NaN
28                                                NaN
29                                                9.0
30                                               Left
31                                                 3
32                                                 3
33                                                  5
34                                          High/High
35                                             Unique
36                                                Yes
37                                            €356.1M
38  Aerial threat,Distance shooter,Strength,Clinic...
39                Acrobatic +,Power Header,Quick Step
40                                                NaN
41                                                NaN
42                                                NaN
43                                                NaN
44                                                NaN
45                                                NaN
46                                               47.0
47                                               96.0
48                                               83.0
49                                               77.0
50                                               90.0
51                                               79.0
52                                               77.0
53                                               62.0
54                                               63.0
55                                               82.0
56                                               82.0
57                                               94.0
58                                                 78
59                                               94.0
60                                                 72
61                                               94.0
62                                               93.0
63                                               76.0
64                                               93.0
65                                               86.0
66                                               87.0
67                                               43.0
68                                               96.0
69                                               74.0
70                                               86.0
71                                               87.0
72                                               38.0
73                                               47.0
74                                               29.0
75                                                7.0
76                                               14.0
77                                               13.0
78                                                 11
79                                                7.0
80                                                NaN
81                                          2023-2024
82                                             240033
83                                               13.0
84          https://cdn.sofifa.net/meta/team/9/30.png
85                                               85.0
86                                                 78
87                             Friendly International
88      https://cdn.sofifa.net/meta/team/18578/30.png
89                                               76.0
90                                                 ST

In [10]:
with open(SOFIFA_INPUT_PATH, 'r', encoding='utf-8') as f:
    headers = f.readline().strip().split(',')
    
    good_sample = None
    bad_sample = None
    
    for line in f:
        if '2022-2023' in line and not good_sample:
            good_sample = line.strip().split(',')
        if '2023-2024' in line and not bad_sample:
            bad_sample = line.strip().split(',')
        if good_sample and bad_sample:
            break

print(f"Header total columns: {len(headers)}")
print(f"22/23 row total elements: {len(good_sample) if good_sample else 'Not found'}")
print(f"23/24 row total elements: {len(bad_sample) if bad_sample else 'Not found'}")

Header total columns: 91
22/23 row total elements: 101
23/24 row total elements: 97

In [11]:
print("=" * 70)
print("DIAGNOSTIC: INSPECTING THE 23/24 PARTIAL TRAP")
print("=" * 70)

# Filter for the 23/24 season partials
trap_df = df_master_partial[df_master_partial['season'] == '2023-2024'].copy()

# Select the critical columns to see exactly why they failed to reach 80 points
cols_to_view = [
    'normalized_name_sswy', 'normalized_name_sof', 
    'normalized_nationality_sswy', 'normalized_nationality_sof', 
    'match_score'
]

pd.set_option('display.max_rows', 20)
print(trap_df[cols_to_view].head(20))

======================================================================
DIAGNOSTIC: INSPECTING THE 23/24 PARTIAL TRAP
======================================================================
     normalized_name_sswy               normalized_name_sof  \
4749          jonny evans              jonathan grant evans
4750           cihan aydn                      ciaran behan
4751           chris wood            christopher grant wood
4752          willi orban                vilmos tamas orban
4753         marko siskov                    marco pissardo
4754            dani olmo              daniel olmo carvajal
4755        lucas masoero        lucas gabriel masoero masi
4756            thalisson         thalisson kelven da silva
4757      mauricio cuevas                   mauricio cuevas
4758            gino vivi                 gino vivi quesada
4759  yahia attiyat allah               yahia attiyat allah
4760           tim kohler                        tim kohler
4761     odilon kossounou                  odilon kossounou
4762       gustavo puerta     gustavo aldolfo puerta molano
4763      patrizio masini                   patrizio masini
4764       justin lonwijk           justin antonius lonwijk
4765          shion homma                       shion homma
4766          igor thiago  igor thiago nascimento rodrigues
4767      federico zuccon                   federico zuccon
4768       valerio crespi                    valerio crespi

     normalized_nationality_sswy normalized_nationality_sof  match_score
4749              united kingdom             united kingdom         79.0
4750                                                                78.4
4751                 new zealand                new zealand         77.2
4752                     hungary                    hungary         77.2
4753                                                                77.2
4754                       spain                      spain         77.2
4755                   argentina                                    75.0
4756                      brazil                                    75.0
4757               united states                                    75.0
4758                  costa rica                                    75.0
4759                     morocco     friendly international         75.0
4760                     germany                                    75.0
4761                 ivory coast                                    75.0
4762                    colombia                                    75.0
4763                       italy                                    75.0
4764                    suriname                                    75.0
4765                       japan                                    75.0
4766                      brazil                                    75.0
4767                       italy                                    75.0
4768                       italy                                    75.0

In [12]:
import pandas as pd

print("\n" + "=" * 80)
print("EXECUTING TARGETED RESCUE FOR CORRUPTED SEASONS (22/23 & 23/24)")
print("=" * 80)

# 1. Define the corrupted seasons
target_seasons = ['2022-2023', '2023-2024']

# 2. Isolate the target seasons from the Unmatched pools
sswy_targets = df_unmatched_sswy[df_unmatched_sswy['season'].isin(target_seasons)]
sof_targets = df_unmatched_sofifa[df_unmatched_sofifa['sofifa_season'].isin(target_seasons)]

# 3. Perform the Pure ID Merge (The Dictionary Cheat Code)
if not sswy_targets.empty and not sof_targets.empty and not rolling_id_dictionary.empty:
    
    rescued_corrupted = sswy_targets.merge(
        rolling_id_dictionary, on='soccersolver_id', how='inner'
    ).merge(
        sof_targets, left_on=['sofifa_player_id', 'season'], right_on=['sofifa_player_id', 'sofifa_season'], suffixes=('_sswy', '_sof')
    )
    
    corrupted_rescue_count = len(rescued_corrupted)
    
    if corrupted_rescue_count > 0:
        # 4. Hardcode the Override flags
        rescued_corrupted['match_score'] = 100.0
        rescued_corrupted['match_status'] = 'MATCHED (RESCUED_CORRUPTED)'
        
        # 5. Append perfectly to Master Matched
        df_master_matched = pd.concat([df_master_matched, rescued_corrupted], ignore_index=True)
        
        # 6. Surgically evict from Unmatched Pools so they do not duplicate
        df_unmatched_sswy = df_unmatched_sswy[~df_unmatched_sswy['soccersolver_id'].isin(rescued_corrupted['soccersolver_id'])]
        df_unmatched_sofifa = df_unmatched_sofifa[~df_unmatched_sofifa['sofifa_player_id'].isin(rescued_corrupted['sofifa_player_id'])]
        
        print(f"SUCCESS: Salvaged {corrupted_rescue_count} players trapped by corrupted names/nationalities.")
    else:
        print(" No exact dictionary matches found in the targeted unmatched pools.")
else:
    print("Missing data in targeted unmatched pools or rolling dictionary is empty.")

# ==========================================
# FINAL RECALCULATED STATISTICS
# ==========================================
print("\n" + "=" * 80)
print(" RECALCULATED FINAL GLOBAL STATISTICS")
print("=" * 80)
print(f"  - Total Matched:          {len(df_master_matched)}  <-- (Increased by {corrupted_rescue_count if 'corrupted_rescue_count' in locals() else 0})")
print(f"  - Total Partial (Review): {len(df_master_partial)}  <-- (Untouched)")
print(f"  - Total Unmatched SSWY:   {len(df_unmatched_sswy)}")
print(f"  - Total Unmatched Sofifa: {len(df_unmatched_sofifa)}")

================================================================================
EXECUTING TARGETED RESCUE FOR CORRUPTED SEASONS (22/23 & 23/24)
================================================================================
 No exact dictionary matches found in the targeted unmatched pools.

================================================================================
 RECALCULATED FINAL GLOBAL STATISTICS
================================================================================
  - Total Matched:          85501  <-- (Increased by 0)
  - Total Partial (Review): 11530  <-- (Untouched)
  - Total Unmatched SSWY:   264704
  - Total Unmatched Sofifa: 35278

In [15]:
print(df_unmatched_sswy.columns.to_list())
print(df_unmatched_sofifa.columns.to_list())

['soccersolver_id', 'name', 'team', 'team_id', 'position_ss', 'main_position', 'age', 'birth_date', 'nationality', 'height', 'preferred_foot', 'shirt_number', 'market_value', 'img_url', 'profile_url', 'season', 'wyscout_id', 'age_years', 'height_cm', 'weight_kg', 'foot', 'position_wy', 'role_code', 'status', 'normalized_name', 'normalized_nationality', 'clean_dob', 'Birth_Year', 'name_first_letter', 'name_initial']
['sofifa_player_id', 'sofifa_fifa_version', 'sofifa_fifa_update', 'sofifa_fifa_update_date', 'sofifa_name', 'sofifa_full_name', 'sofifa_positions', 'sofifa_overall_rating', 'sofifa_potential', 'sofifa_value', 'sofifa_wage', 'sofifa_age', 'sofifa_dob', 'sofifa_height_cm', 'sofifa_weight_kg', 'sofifa_league_id', 'sofifa_club_league_name', 'sofifa_league_level', 'sofifa_club_id', 'sofifa_club_name', 'sofifa_club_position', 'sofifa_club_kit_number', 'sofifa_club_loaned_from', 'sofifa_club_joined', 'sofifa_club_contract_valid_until', 'sofifa_country_id', 'sofifa_country_name', 'sofifa_nation_team_id', 'sofifa_nation_position', 'sofifa_country_kit_number', 'sofifa_preferred_foot', 'sofifa_weak_foot', 'sofifa_moves', 'sofifa_international_reputation', 'sofifa_work_rate', 'sofifa_body_type', 'sofifa_real_face', 'sofifa_release_clause', 'sofifa_specialities', 'sofifa_play_styles', 'sofifa_pace', 'sofifa_shooting', 'sofifa_passing', 'sofifa_macro_dribbling', 'sofifa_defending', 'sofifa_physic', 'sofifa_crossing', 'sofifa_finishing', 'sofifa_heading_accuracy', 'sofifa_short_passing', 'sofifa_volleys', 'sofifa_dribbling', 'sofifa_curve', 'sofifa_fk_accuracy', 'sofifa_long_passing', 'sofifa_ball_control', 'sofifa_acceleration', 'sofifa_sprint_speed', 'sofifa_agility', 'sofifa_reactions', 'sofifa_balance', 'sofifa_shot_power', 'sofifa_jumping', 'sofifa_stamina', 'sofifa_strength', 'sofifa_long_shots', 'sofifa_aggression', 'sofifa_interceptions', 'sofifa_positioning', 'sofifa_vision', 'sofifa_penalties', 'sofifa_composure', 'sofifa_defensive_awareness', 'sofifa_standing_tackle', 'sofifa_sliding_tackle', 'sofifa_gk_diving', 'sofifa_gk_handling', 'sofifa_gk_kicking', 'sofifa_gk_positioning', 'sofifa_gk_reflexes', 'sofifa_gk_speed', 'sofifa_season', 'sofifa_version', 'sofifa_club_league_id', 'sofifa_club_logo', 'sofifa_club_rating', 'sofifa_country_league_id', 'sofifa_country_league_name', 'sofifa_country_flag', 'sofifa_country_rating', 'sofifa_country_position', 'normalized_name', 'normalized_nationality', 'clean_dob', 'Birth_Year', 'name_first_letter']

In [17]:
import pandas as pd
import numpy as np
from thefuzz import fuzz

# ==============================================================================
# 1. PRE-PROCESSING: ENSURE STRINGS & FIX FLOAT IDS
# ==============================================================================
# Apply your ID guardrail to the specific primary keys
df_unmatched_sswy['soccersolver_id'] = df_unmatched_sswy['soccersolver_id'].astype(str).str.replace(r'\.0$', '', regex=True)
df_unmatched_sofifa['sofifa_player_id'] = df_unmatched_sofifa['sofifa_player_id'].astype(str).str.replace(r'\.0$', '', regex=True)

# Sort seasons to guarantee chronological learning (using SSWY's season column)
seasons = sorted(df_unmatched_sswy['season'].dropna().unique())
total_seasons = len(seasons)

# ==============================================================================
# GUARDRAIL: SANITIZE THE ROLLING DICTIONARY
# ==============================================================================
# If rolling_id_dictionary is a DataFrame, convert it to a dict
if isinstance(rolling_id_dictionary, pd.DataFrame):
    # Swap 'soccersolver_id' and 'sofifa_player_id' with your actual column names if they differ in the DF
    rolling_id_dictionary = dict(zip(
        rolling_id_dictionary['soccersolver_id'].astype(str), 
        rolling_id_dictionary['sofifa_player_id'].astype(str)
    ))
elif isinstance(rolling_id_dictionary, dict):
    # If it is a dict, force all keys and values to be flat 1D strings to strip any hidden Pandas Series/Arrays
    rolling_id_dictionary = {str(k): str(v) for k, v in rolling_id_dictionary.items()}
else:
    raise TypeError(f"rolling_id_dictionary is an unexpected type: {type(rolling_id_dictionary)}")

# ==============================================================================
# 2. THE CHRONOLOGICAL SNOWBALL ENGINE
# ==============================================================================
for idx, season in enumerate(seasons, start=1):
    
    # Tracker Variables setup
    dict_size_start = len(rolling_id_dictionary)
    vip_match_count = 0
    candidate_count = 0
    new_matched_count = 0
    new_partial_count = 0
    
    # Isolate current season using respective season columns
    sswy_season = df_unmatched_sswy[df_unmatched_sswy['season'] == season].copy()
    sofifa_season = df_unmatched_sofifa[df_unmatched_sofifa['sofifa_season'] == season].copy()
    
    if sswy_season.empty or sofifa_season.empty:
        continue

    # --------------------------------------------------------------------------
    # STEP A: THE VIP DICTIONARY BYPASS
    # --------------------------------------------------------------------------
    sswy_season['mapped_sofifa'] = sswy_season['soccersolver_id'].map(rolling_id_dictionary)
    vip_matches = sswy_season.dropna(subset=['mapped_sofifa'])
    vip_matches = vip_matches[vip_matches['mapped_sofifa'].isin(sofifa_season['sofifa_player_id'])]
    
    if not vip_matches.empty:
        vip_to_append = pd.merge(
            vip_matches, 
            sofifa_season, 
            left_on='mapped_sofifa', 
            right_on='sofifa_player_id', 
            suffixes=('_sswy', '_sofifa')
        )
        vip_to_append['match_score'] = 100 
        vip_to_append['match_type'] = 'VIP_BYPASS_SECONDARY'
        
        df_master_matched = pd.concat([df_master_matched, vip_to_append], ignore_index=True)
        
        sswy_season = sswy_season[~sswy_season['soccersolver_id'].isin(vip_to_append['soccersolver_id'])]
        sofifa_season = sofifa_season[~sofifa_season['sofifa_player_id'].isin(vip_to_append['sofifa_player_id'])]
        
        vip_match_count = len(vip_to_append)

    leftovers_count = len(sofifa_season)

    # --------------------------------------------------------------------------
    # STEP B: THE GATED HEURISTIC EVALUATION
    # --------------------------------------------------------------------------
    # GATE 1: The Merge (Normalized Nationality + First Letter)
    merged_pool = pd.merge(
        sswy_season, 
        sofifa_season, 
        on=['normalized_nationality', 'name_first_letter'], 
        suffixes=('_sswy', '_sofifa')
    )
    
    if not merged_pool.empty:
        # GATE 2: Physical Tolerances (Height OR Foot fallback)
        cond_height = (merged_pool['height_cm'] - merged_pool['sofifa_height_cm']).abs() <= 3
        cond_foot = merged_pool['height_cm'].isna() & (merged_pool['preferred_foot'] == merged_pool['sofifa_preferred_foot'])
        
        merged_pool = merged_pool[cond_height | cond_foot].copy()
        candidate_count = len(merged_pool)
        
        if not merged_pool.empty:
            # GATE 3: String Evaluation (using normalized names)
            merged_pool['name_score'] = merged_pool.apply(
                lambda row: fuzz.token_set_ratio(str(row['normalized_name_sswy']), str(row['normalized_name_sofifa'])), 
                axis=1
            )
            
            matched_mask = merged_pool['name_score'] > 85
            partial_mask = (merged_pool['name_score'] >= 75) & (merged_pool['name_score'] <= 85)
            
            new_matched = merged_pool[matched_mask].copy()
            new_partial = merged_pool[partial_mask].copy()
            
            if not new_matched.empty:
                new_matched['match_type'] = 'SECONDARY_HEURISTIC_MATCH'
                df_master_matched = pd.concat([df_master_matched, new_matched], ignore_index=True)
                
                # Update rolling dictionary using exact ID columns
                new_dict_entries = dict(zip(new_matched['soccersolver_id'], new_matched['sofifa_player_id']))
                rolling_id_dictionary.update(new_dict_entries)
                new_matched_count = len(new_matched)
                
            if not new_partial.empty:
                new_partial['match_type'] = 'SECONDARY_HEURISTIC_PARTIAL'
                df_master_partial = pd.concat([df_master_partial, new_partial], ignore_index=True)
                new_partial_count = len(new_partial)

    # --------------------------------------------------------------------------
    # LIVE TRACKER CONSOLE OUTPUT
    # --------------------------------------------------------------------------
    print(f"\n[{idx}/{total_seasons}] LIVE TRACKER: Season {season}")
    print("-" * 80)
    print(f" -> VIP Bypass:             {vip_match_count:<5} Matched (Current Dictionary Size: {dict_size_start})")
    print(f"    [Rookies/Leftovers pushed to Heuristics: {leftovers_count} Sofifa Players]")
    print(f" -> Gates 1 & 2 (Physical): {candidate_count:<5} Survived to String Evaluation")
    print(f" -> Gate 3 (String Score):  {new_matched_count:<5} Matched (>85%) | {new_partial_count} Partial (75-85%)")
    if new_matched_count > 0:
        print(f" [+] Added {new_matched_count} newly discovered pairs to the Rolling Dictionary.")

# ==============================================================================
# 3. THE RETROACTIVE LOOP-BACK (TIME MACHINE)
# ==============================================================================
print("\n" + "=" * 80)
print("Executing Retroactive Time Machine Pass...")

df_unmatched_sswy['retro_mapped_sofifa'] = df_unmatched_sswy['soccersolver_id'].map(rolling_id_dictionary)
retro_rescued_sswy = df_unmatched_sswy.dropna(subset=['retro_mapped_sofifa'])

if not retro_rescued_sswy.empty:
    retro_rescued_full = pd.merge(
        retro_rescued_sswy,
        df_unmatched_sofifa,
        left_on=['retro_mapped_sofifa', 'season'],
        right_on=['sofifa_player_id', 'sofifa_season'], # Aligning disparate season columns
        suffixes=('_sswy', '_sofifa')
    )
    
    retro_rescued_full['match_score'] = 100
    retro_rescued_full['match_type'] = 'RETROACTIVE_RESCUE_SECONDARY'
    df_master_matched = pd.concat([df_master_matched, retro_rescued_full], ignore_index=True)
    
    print(f" [*] Retroactive Sweep Complete: Rescued {len(retro_rescued_full)} historical records.")

# ==============================================================================
# 4. THE FINAL PURGE (Hygiene Maintenance)
# ==============================================================================
print("Purging Matched/Partial records from Unmatched datasets...")

resolved_sswy_ids = set(df_master_matched['soccersolver_id']).union(set(df_master_partial['soccersolver_id']))
resolved_sofifa_ids = set(df_master_matched['sofifa_player_id']).union(set(df_master_partial['sofifa_player_id']))

df_unmatched_sswy = df_unmatched_sswy[~df_unmatched_sswy['soccersolver_id'].isin(resolved_sswy_ids)]
df_unmatched_sofifa = df_unmatched_sofifa[~df_unmatched_sofifa['sofifa_player_id'].isin(resolved_sofifa_ids)]

df_unmatched_sswy.drop(columns=['retro_mapped_sofifa'], errors='ignore', inplace=True)

print("Secondary Pipeline Execution Complete.\n" + "=" * 80)

[1/7] LIVE TRACKER: Season 2019-2020
--------------------------------------------------------------------------------
 -> VIP Bypass:             0     Matched (Current Dictionary Size: 26799)
    [Rookies/Leftovers pushed to Heuristics: 4829 Sofifa Players]
 -> Gates 1 & 2 (Physical): 43715 Survived to String Evaluation
 -> Gate 3 (String Score):  1123  Matched (>85%) | 230 Partial (75-85%)
 [+] Added 1123 newly discovered pairs to the Rolling Dictionary.

[2/7] LIVE TRACKER: Season 2020-2021
--------------------------------------------------------------------------------
 -> VIP Bypass:             736   Matched (Current Dictionary Size: 27728)
    [Rookies/Leftovers pushed to Heuristics: 4602 Sofifa Players]
 -> Gates 1 & 2 (Physical): 41739 Survived to String Evaluation
 -> Gate 3 (String Score):  492   Matched (>85%) | 204 Partial (75-85%)
 [+] Added 492 newly discovered pairs to the Rolling Dictionary.

[3/7] LIVE TRACKER: Season 2021-2022
--------------------------------------------------------------------------------
 -> VIP Bypass:             856   Matched (Current Dictionary Size: 28145)
    [Rookies/Leftovers pushed to Heuristics: 4464 Sofifa Players]
 -> Gates 1 & 2 (Physical): 37821 Survived to String Evaluation
 -> Gate 3 (String Score):  413   Matched (>85%) | 196 Partial (75-85%)
 [+] Added 413 newly discovered pairs to the Rolling Dictionary.

[4/7] LIVE TRACKER: Season 2022-2023
--------------------------------------------------------------------------------
 -> VIP Bypass:             909   Matched (Current Dictionary Size: 28487)
    [Rookies/Leftovers pushed to Heuristics: 4680 Sofifa Players]
 -> Gates 1 & 2 (Physical): 34492 Survived to String Evaluation
 -> Gate 3 (String Score):  463   Matched (>85%) | 294 Partial (75-85%)
 [+] Added 463 newly discovered pairs to the Rolling Dictionary.

[5/7] LIVE TRACKER: Season 2023-2024
--------------------------------------------------------------------------------
 -> VIP Bypass:             935   Matched (Current Dictionary Size: 28859)
    [Rookies/Leftovers pushed to Heuristics: 4323 Sofifa Players]
 -> Gates 1 & 2 (Physical): 49459 Survived to String Evaluation
 -> Gate 3 (String Score):  16    Matched (>85%) | 46 Partial (75-85%)
 [+] Added 16 newly discovered pairs to the Rolling Dictionary.

[6/7] LIVE TRACKER: Season 2024-2025
--------------------------------------------------------------------------------
 -> VIP Bypass:             848   Matched (Current Dictionary Size: 28873)
    [Rookies/Leftovers pushed to Heuristics: 4120 Sofifa Players]
 -> Gates 1 & 2 (Physical): 37831 Survived to String Evaluation
 -> Gate 3 (String Score):  21    Matched (>85%) | 22 Partial (75-85%)
 [+] Added 21 newly discovered pairs to the Rolling Dictionary.

[7/7] LIVE TRACKER: Season 2025-2026
--------------------------------------------------------------------------------
 -> VIP Bypass:             835   Matched (Current Dictionary Size: 28890)
    [Rookies/Leftovers pushed to Heuristics: 4130 Sofifa Players]
 -> Gates 1 & 2 (Physical): 35783 Survived to String Evaluation
 -> Gate 3 (String Score):  820   Matched (>85%) | 219 Partial (75-85%)
 [+] Added 820 newly discovered pairs to the Rolling Dictionary.

================================================================================
Executing Retroactive Time Machine Pass...
 [*] Retroactive Sweep Complete: Rescued 10255 historical records.
Purging Matched/Partial records from Unmatched datasets...
Secondary Pipeline Execution Complete.
================================================================================

In [18]:
# ==============================================================================
# FINAL DIAGNOSTIC REPORT: SECONDARY SNOWBALL PIPELINE
# ==============================================================================

print("\n" + "=" * 80)
print("               FINAL DIAGNOSTIC REPORT: DOB-MISSING RESCUE RUN          ")
print("=" * 80)

# 1. Extract Counts from Master Files using the secondary match_type tags
secondary_vip = len(df_master_matched[df_master_matched['match_type'] == 'VIP_BYPASS_SECONDARY']) if 'match_type' in df_master_matched.columns else 0
secondary_heur = len(df_master_matched[df_master_matched['match_type'] == 'SECONDARY_HEURISTIC_MATCH']) if 'match_type' in df_master_matched.columns else 0
secondary_retro = len(df_master_matched[df_master_matched['match_type'] == 'RETROACTIVE_RESCUE_SECONDARY']) if 'match_type' in df_master_matched.columns else 0
secondary_partial = len(df_master_partial[df_master_partial['match_type'] == 'SECONDARY_HEURISTIC_PARTIAL']) if 'match_type' in df_master_partial.columns else 0

total_rescued_matches = secondary_vip + secondary_heur + secondary_retro

# 2. Extract Current Unmatched Volumes
remaining_unmatched_sswy = len(df_unmatched_sswy)
remaining_unmatched_sofifa = len(df_unmatched_sofifa)

# 3. Calculate Season-wise Residuals
print("1. PIPELINE IMPACT METRICS")
print("-" * 80)
print(f" -> Total Players Promoted to MATCHED : {total_rescued_matches:<5}")
print(f"    │  ├── Via Historical VIP Bypass  : {secondary_vip:<5}")
print(f"    │  ├── Via Gated Heuristics (>85%): {secondary_heur:<5}")
print(f"    │  └── Via Retroactive Time Machine: {secondary_retro:<5}")
print(f" -> Total Players Sent to PARTIAL      : {secondary_partial:<5} (75%-85% Name Match, No DOB)")

print("\n2. KNOWLEDGE BASE GROWTH")
print("-" * 80)
print(f" -> Final Rolling Dictionary Size      : {len(rolling_id_dictionary):<5} unique identities mapped")

print("\n3. POST-RUN DATASET CLEANLINESS (REMAINING POOL)")
print("-" * 80)
print(f" -> Remaining Unmatched SSWY Rows     : {remaining_unmatched_sswy:<5}")
print(f" -> Remaining Unmatched Sofifa Rows   : {remaining_unmatched_sofifa:<5}")

print("\n4. REMAINING UNMATCHED BREAKDOWN BY SEASON")
print("-" * 80)
# Updated to use exact season column names from your schemas
sswy_season_counts = df_unmatched_sswy['season'].value_counts().to_dict() if 'season' in df_unmatched_sswy.columns else {}
sofifa_season_counts = df_unmatched_sofifa['sofifa_season'].value_counts().to_dict() if 'sofifa_season' in df_unmatched_sofifa.columns else {}

all_seasons = sorted(list(set(sswy_season_counts.keys()).union(set(sofifa_season_counts.keys()))))

print(f"{'Season':<15} | {'Remaining SSWY Unmatched':<25} | {'Remaining Sofifa Unmatched':<25}")
print("-" * 80)
for s in all_seasons:
    sswy_cnt = sswy_season_counts.get(s, 0)
    sof_cnt = sofifa_season_counts.get(s, 0)
    print(f"{s:<15} | {sswy_cnt:<25} | {sof_cnt:<25}")

print("=" * 80 + "\n")

================================================================================
               FINAL DIAGNOSTIC REPORT: DOB-MISSING RESCUE RUN
================================================================================
1. PIPELINE IMPACT METRICS
--------------------------------------------------------------------------------
 -> Total Players Promoted to MATCHED : 18722
    │  ├── Via Historical VIP Bypass  : 5119
    │  ├── Via Gated Heuristics (>85%): 3348
    │  └── Via Retroactive Time Machine: 10255
 -> Total Players Sent to PARTIAL      : 1211  (75%-85% Name Match, No DOB)

2. KNOWLEDGE BASE GROWTH
--------------------------------------------------------------------------------
 -> Final Rolling Dictionary Size      : 29481 unique identities mapped

3. POST-RUN DATASET CLEANLINESS (REMAINING POOL)
--------------------------------------------------------------------------------
 -> Remaining Unmatched SSWY Rows     : 189824
 -> Remaining Unmatched Sofifa Rows   : 21084

4. REMAINING UNMATCHED BREAKDOWN BY SEASON
--------------------------------------------------------------------------------
Season          | Remaining SSWY Unmatched  | Remaining Sofifa Unmatched
--------------------------------------------------------------------------------
2019-2020       | 26121                     | 2938
2020-2021       | 26260                     | 3021
2021-2022       | 26673                     | 3015
2022-2023       | 26533                     | 3168
2023-2024       | 28589                     | 3029
2024-2025       | 30239                     | 2892
2025-2026       | 25409                     | 3021
================================================================================

In [19]:
# ==============================================================================
# FINAL DATAFRAME LENGTHS
# ==============================================================================
print("\n" + "=" * 80)
print("                      FINAL DATAFRAME ROW COUNTS                        ")
print("=" * 80)
print(f" -> df_master_matched:     {len(df_master_matched):,} rows")
print(f" -> df_master_partial:     {len(df_master_partial):,} rows")
print(f" -> df_unmatched_sswy:     {len(df_unmatched_sswy):,} rows")
print(f" -> df_unmatched_sofifa:   {len(df_unmatched_sofifa):,} rows")
print("=" * 80 + "\n")

================================================================================
                      FINAL DATAFRAME ROW COUNTS
================================================================================
 -> df_master_matched:     104,223 rows
 -> df_master_partial:     12,741 rows
 -> df_unmatched_sswy:     189,824 rows
 -> df_unmatched_sofifa:   21,084 rows
================================================================================

In [ ]:
# Uncomment to export your final tables
df_master_matched.to_csv("newdata/players/matched/FINAL_MATCHED_MASTER.csv", index=False)
df_master_partial.to_csv("newdata/players/partial match/FINAL_PARTIAL_REVIEW.csv", index=False)
df_unmatched_sswy.to_csv("newdata/players/no match/UNMATCHED_SSWY.csv", index=False)
df_unmatched_sofifa.to_csv("newdata/players/no match/UNMATCHED_SOFIFA.csv", index=False)

In [ ]:
# Convert the dictionary back to a 2-column DataFrame before saving
pd.DataFrame(list(rolling_id_dictionary.items()), columns=['soccersolver_id', 'sofifa_player_id']).to_csv("newdata/players/matched/FINAL_ID_DICTIONARY.csv", index=False)
# rolling_id_dictionary.to_csv("newdata/players/matched/FINAL_ID_DICTIONARY.csv", index=False)

In [24]:
print(df_master_partial.columns.to_list())

['soccersolver_id', 'name', 'team', 'team_id', 'position_ss', 'main_position', 'age', 'birth_date', 'nationality', 'height', 'preferred_foot', 'shirt_number', 'market_value', 'img_url', 'profile_url', 'season', 'wyscout_id', 'age_years', 'height_cm', 'weight_kg', 'foot', 'position_wy', 'role_code', 'status', 'normalized_name_sswy', 'normalized_nationality_sswy', 'clean_dob', 'Birth_Year_sswy', 'name_first_letter_sswy', 'sofifa_player_id', 'sofifa_fifa_version', 'sofifa_fifa_update', 'sofifa_fifa_update_date', 'sofifa_name', 'sofifa_full_name', 'sofifa_positions', 'sofifa_overall_rating', 'sofifa_potential', 'sofifa_value', 'sofifa_wage', 'sofifa_age', 'sofifa_dob', 'sofifa_height_cm', 'sofifa_weight_kg', 'sofifa_league_id', 'sofifa_club_league_name', 'sofifa_league_level', 'sofifa_club_id', 'sofifa_club_name', 'sofifa_club_position', 'sofifa_club_kit_number', 'sofifa_club_loaned_from', 'sofifa_club_joined', 'sofifa_club_contract_valid_until', 'sofifa_country_id', 'sofifa_country_name', 'sofifa_nation_team_id', 'sofifa_nation_position', 'sofifa_country_kit_number', 'sofifa_preferred_foot', 'sofifa_weak_foot', 'sofifa_moves', 'sofifa_international_reputation', 'sofifa_work_rate', 'sofifa_body_type', 'sofifa_real_face', 'sofifa_release_clause', 'sofifa_specialities', 'sofifa_play_styles', 'sofifa_pace', 'sofifa_shooting', 'sofifa_passing', 'sofifa_macro_dribbling', 'sofifa_defending', 'sofifa_physic', 'sofifa_crossing', 'sofifa_finishing', 'sofifa_heading_accuracy', 'sofifa_short_passing', 'sofifa_volleys', 'sofifa_dribbling', 'sofifa_curve', 'sofifa_fk_accuracy', 'sofifa_long_passing', 'sofifa_ball_control', 'sofifa_acceleration', 'sofifa_sprint_speed', 'sofifa_agility', 'sofifa_reactions', 'sofifa_balance', 'sofifa_shot_power', 'sofifa_jumping', 'sofifa_stamina', 'sofifa_strength', 'sofifa_long_shots', 'sofifa_aggression', 'sofifa_interceptions', 'sofifa_positioning', 'sofifa_vision', 'sofifa_penalties', 'sofifa_composure', 'sofifa_defensive_awareness', 'sofifa_standing_tackle', 'sofifa_sliding_tackle', 'sofifa_gk_diving', 'sofifa_gk_handling', 'sofifa_gk_kicking', 'sofifa_gk_positioning', 'sofifa_gk_reflexes', 'sofifa_gk_speed', 'sofifa_season', 'sofifa_version', 'sofifa_club_league_id', 'sofifa_club_logo', 'sofifa_club_rating', 'sofifa_country_league_id', 'sofifa_country_league_name', 'sofifa_country_flag', 'sofifa_country_rating', 'sofifa_country_position', 'normalized_name_sof', 'normalized_nationality_sof', 'Birth_Year_sof', 'name_first_letter_sof', 'match_score', 'match_status', 'normalized_nationality', 'clean_dob_sswy', 'Birth_Year', 'clean_dob_sof', 'name_first_letter', 'name_initial', 'mapped_sofifa', 'normalized_name_sofifa', 'clean_dob_sofifa', 'Birth_Year_sofifa', 'name_score', 'match_type']

In [25]:
columns_to_keep = [
    'soccersolver_id', 'sofifa_player_id', 'season',
    'name', 'normalized_name_sswy', 'sofifa_name', 'sofifa_full_name', 'normalized_name_sof',
    'nationality', 'normalized_nationality_sswy', 'sofifa_country_name', 'normalized_nationality_sof',
    'clean_dob_sswy', 'sofifa_dob',
    'height_cm', 'sofifa_height_cm', 'team', 'sofifa_club_name', 'main_position', 'sofifa_positions',
    'name_score', 'match_score', 'match_type'
]

# Extract the columns (ignoring any that might be named slightly differently)
existing_cols = [col for col in columns_to_keep if col in df_master_partial.columns]

# Grab 40 rows that specifically include the problematic 23/24 or 24/25 seasons
sample_df = df_master_partial[df_master_partial['season'].isin(['2023-2024', '2024-2025'])][existing_cols].head(40)

# Export to a clean CSV to upload
sample_df.to_csv("newdata/players/partial match/partial_sample_for_review.csv", index=False)

In [2]:
import pandas as pd
import numpy as np
from thefuzz import fuzz

# ==============================================================================
# 1. LOAD DATA & SANITIZE DICTIONARY
# ==============================================================================
print("Loading datasets...")
df_partial = pd.read_csv("newdata/players/partial match/FINAL_PARTIAL_REVIEW.csv")
df_matched = pd.read_csv("newdata/players/matched/FINAL_MATCHED_MASTER.csv")
df_unmatched_sswy = pd.read_csv("newdata/players/no match/UNMATCHED_SSWY.csv")
df_unmatched_sofifa = pd.read_csv("newdata/players/no match/UNMATCHED_SOFIFA.csv")

# Ensure dictionary is loaded and sanitized to a flat 1D string mapping
dict_df = pd.read_csv("newdata/players/matched/FINAL_ID_DICTIONARY.csv")
rolling_id_dictionary = dict(zip(dict_df['soccersolver_id'].astype(str), dict_df['sofifa_player_id'].astype(str)))

# Ensure IDs are strings in the partial file for clean lookups
df_partial['soccersolver_id'] = df_partial['soccersolver_id'].astype(str).str.replace(r'\.0$', '', regex=True)
df_partial['sofifa_player_id'] = df_partial['sofifa_player_id'].astype(str).str.replace(r'\.0$', '', regex=True)

# ==============================================================================
# 2. EXTRACT MASTER TEAM DICTIONARY (Ground Truth)
# ==============================================================================
valid_teams = df_matched.dropna(subset=['team', 'sofifa_club_name'])
master_team_set = set(zip(valid_teams['team'].str.lower(), valid_teams['sofifa_club_name'].str.lower()))
print(f"Extracted {len(master_team_set)} verified Team-to-Club pairings from Master.")

# ==============================================================================
# 3. DEFINE THE FALLBACK EVALUATOR
# ==============================================================================
def evaluate_partial_row(row):
    sswy_name = str(row.get('normalized_name_sswy', row.get('name', ''))).lower()
    sof_short = str(row.get('normalized_name_sof', row.get('sofifa_name', ''))).lower()
    sof_full = str(row.get('sofifa_full_name', '')).lower()
    
    sswy_team = str(row.get('team', '')).lower()
    sof_team = str(row.get('sofifa_club_name', '')).lower()
    
    dob_sswy = str(row.get('clean_dob_sswy', 'nan'))
    dob_sof = str(row.get('sofifa_dob', 'nan'))
    
    nat_sswy = str(row.get('normalized_nationality_sswy', 'nan')).lower()
    nat_sof = str(row.get('normalized_nationality_sof', 'nan')).lower()
    
    foot_sswy = str(row.get('preferred_foot', 'nan')).lower()
    foot_sof = str(row.get('sofifa_preferred_foot', 'nan')).lower()
    
    h_sswy = row.get('height_cm')
    h_sof = row.get('sofifa_height_cm')
    height_match = False
    if pd.notna(h_sswy) and pd.notna(h_sof):
        height_match = abs(float(h_sswy) - float(h_sof)) <= 2

    # Calculate best name score
    best_name_score = max(fuzz.token_set_ratio(sswy_name, sof_short), fuzz.token_set_ratio(sswy_name, sof_full))
    
    # GLOBAL STEP 1: The Master Team Anchor
    if sswy_team != 'nan' and sof_team != 'nan' and (sswy_team, sof_team) in master_team_set:
        if best_name_score >= 70:
            return 'TEAM_ANCHOR'
            
    # GLOBAL STEP 2: The Fallback Logic
    has_dob = (dob_sswy != 'nan' and dob_sof != 'nan' and dob_sswy != '' and dob_sof != '')
    foot_match = (foot_sswy != 'nan' and foot_sswy == foot_sof)
    nat_match = (nat_sswy != 'nan' and nat_sswy == nat_sof)

    if has_dob:
        # CASE 1: DOB Present
        if dob_sswy == dob_sof and nat_match:
            if foot_match or height_match:
                if best_name_score >= 70:  # Name safety net
                    return 'CASE_1_DOB'
    else:
        # CASE 2: DOB Missing
        if nat_match and foot_match and height_match:
            if best_name_score >= 80:
                return 'CASE_2_NO_DOB'
                
    return 'REJECTED'

# ==============================================================================
# 4. CHRONOLOGICAL LOOP & EVALUATION (With Live Tracker)
# ==============================================================================
df_partial['rescue_status'] = 'PENDING'
seasons = sorted(df_partial['season'].dropna().unique())

print("\n" + "="*50)
print("STARTING SNOWBALL RESCUE ENGINE RUN")
print("="*50)

for idx, season in enumerate(seasons, 1):
    season_mask = df_partial['season'] == season
    total_season_records = season_mask.sum()
    
    # Global Step 0: VIP Bypass
    mapped_sofifa = df_partial.loc[season_mask, 'soccersolver_id'].map(rolling_id_dictionary)
    vip_mask = mapped_sofifa == df_partial.loc[season_mask, 'sofifa_player_id']
    num_vip = vip_mask.sum()
    
    # Apply VIP statuses
    df_partial.loc[season_mask & vip_mask, 'rescue_status'] = 'VIP_BYPASS'
    
    # Live tracker console header
    print(f"\nProcessing Season [{idx}/{len(seasons)}]: {season}")
    print(f" -> Total records in season: {total_season_records}")
    print(f" -> VIP Bypass matches found: {num_vip}")
    
    # Evaluate Leftovers
    leftover_mask = season_mask & ~vip_mask
    num_leftovers = leftover_mask.sum()
    
    if num_leftovers > 0:
        print(f" -> Running fallback heuristics on remaining {num_leftovers} rows...")
        df_partial.loc[leftover_mask, 'rescue_status'] = df_partial[leftover_mask].apply(evaluate_partial_row, axis=1)
        
        # Count outcomes for this season's fallback execution
        season_results = df_partial[leftover_mask]['rescue_status'].value_counts()
        for status, count in season_results.items():
            print(f"    - {status}: {count}")
            
        # Snowball Update: Add new approvals from this season to the dictionary
        new_approvals = df_partial[leftover_mask & (df_partial['rescue_status'] != 'REJECTED')]
        new_dict_entries = dict(zip(new_approvals['soccersolver_id'], new_approvals['sofifa_player_id']))
        rolling_id_dictionary.update(new_dict_entries)
    else:
        print(" -> No remaining rows to process via fallback heuristics.")

print("\n" + "="*50)
print("RUNNING RETROACTIVE SWEEP (TIME MACHINE)")
print("="*50)

# Phase 4: Retroactive Sweep (Time Machine)
retro_mask = df_partial['rescue_status'] == 'REJECTED'
num_initial_rejected = retro_mask.sum()
print(f"Initial rejected rows across all seasons: {num_initial_rejected}")

mapped_retro = df_partial.loc[retro_mask, 'soccersolver_id'].map(rolling_id_dictionary)
retro_success_mask = mapped_retro == df_partial.loc[retro_mask, 'sofifa_player_id']
num_retro_rescued = retro_success_mask.sum()

df_partial.loc[retro_mask & retro_success_mask, 'rescue_status'] = 'RETROACTIVE_RESCUE'
print(f" -> Successfully rescued via Retroactive Matured Dictionary: {num_retro_rescued}")

# ==============================================================================
# 5. FINAL ROUTING & SAVING (Collision-Proof)
# ==============================================================================
approved_mask = df_partial['rescue_status'] != 'REJECTED'
approved_records = df_partial[approved_mask].copy()
rejected_records = df_partial[~approved_mask].copy()

print("\n" + "="*50)
print("FINAL PIPELINE EXECUTION SUMMARY")
print("="*50)
print(approved_records['rescue_status'].value_counts())
print(f"Total True False-Positives (Sent to Unmatched): {len(rejected_records)}")
print("="*50)

# ROUTE 1: Append Approved to Master Matched
approved_records['match_type'] = 'PARTIAL_RESCUE_' + approved_records['rescue_status']
approved_records.drop(columns=['rescue_status'], inplace=True)
df_matched = pd.concat([df_matched, approved_records], ignore_index=True)

# ROUTE 2: Un-merge Rejected back to Unmatched Files (Collision-Proof mapping)
rejected_sswy = pd.DataFrame()
for col in df_unmatched_sswy.columns:
    if f"{col}_sswy" in rejected_records.columns:
        rejected_sswy[col] = rejected_records[f"{col}_sswy"]
    elif col in rejected_records.columns:
        rejected_sswy[col] = rejected_records[col]
    else:
        rejected_sswy[col] = np.nan

rejected_sofifa = pd.DataFrame()
for col in df_unmatched_sofifa.columns:
    if f"{col}_sof" in rejected_records.columns:
        rejected_sofifa[col] = rejected_records[f"{col}_sof"]
    elif f"{col}_sofifa" in rejected_records.columns:
        rejected_sofifa[col] = rejected_records[f"{col}_sofifa"]
    elif col in rejected_records.columns:
        rejected_sofifa[col] = rejected_records[col]
    else:
        rejected_sofifa[col] = np.nan

# Append back to respective unmatched files
df_unmatched_sswy = pd.concat([df_unmatched_sswy, rejected_sswy], ignore_index=True)
df_unmatched_sofifa = pd.concat([df_unmatched_sofifa, rejected_sofifa], ignore_index=True)

# Save all files
print("\nSaving updated Master and Unmatched files...")
df_matched.to_csv("newdata/players/matched/FINAL_MATCHED_MASTER.csv", index=False)
df_unmatched_sswy.to_csv("newdata/players/no match/UNMATCHED_SSWY.csv", index=False)
df_unmatched_sofifa.to_csv("newdata/players/no match/UNMATCHED_SOFIFA.csv", index=False)

# Empty out the Partial file and overwrite it
pd.DataFrame(columns=df_partial.columns).to_csv("newdata/players/partial match/FINAL_PARTIAL_REVIEW.csv", index=False)

# Save the updated dictionary
pd.DataFrame(list(rolling_id_dictionary.items()), columns=['soccersolver_id', 'sofifa_player_id']).to_csv("newdata/players/matched/FINAL_ID_DICTIONARY.csv", index=False)

print("Process Complete. The Partial File has been cleanly drained.")

Loading datasets...

C:\Users\ashwy\AppData\Local\Temp\ipykernel_15664\2001095214.py:9: DtypeWarning: Columns (0: normalized_nationality_sswy, 1: clean_dob, 2: name_first_letter_sswy, 3: sofifa_value, 4: sofifa_wage, 5: sofifa_club_contract_valid_until, 6: sofifa_weak_foot, 7: sofifa_release_clause, 8: sofifa_agility, 9: sofifa_balance, 10: sofifa_gk_positioning, 11: sofifa_version, 12: sofifa_club_logo, 13: sofifa_country_league_id, 14: sofifa_country_league_name, 15: sofifa_country_flag, 16: sofifa_country_position, 17: normalized_name_sof, 18: normalized_nationality_sof, 19: name_first_letter_sof, 20: match_status, 21: clean_dob_sof, 22: name_initial, 23: normalized_name_sofifa, 24: clean_dob_sofifa, 25: match_type) have mixed types. Specify dtype option on import or set low_memory=False.
  df_partial = pd.read_csv("newdata/players/partial match/FINAL_PARTIAL_REVIEW.csv")
C:\Users\ashwy\AppData\Local\Temp\ipykernel_15664\2001095214.py:10: DtypeWarning: Columns (0: clean_dob, 1: sofifa_fifa_update_date, 2: sofifa_value, 3: sofifa_wage, 4: sofifa_club_loaned_from, 5: sofifa_club_contract_valid_until, 6: sofifa_nation_position, 7: sofifa_weak_foot, 8: sofifa_moves, 9: sofifa_international_reputation, 10: sofifa_work_rate, 11: sofifa_release_clause, 12: sofifa_play_styles, 13: sofifa_agility, 14: sofifa_balance, 15: sofifa_gk_positioning, 16: sofifa_version, 17: sofifa_club_logo, 18: sofifa_country_league_id, 19: sofifa_country_league_name, 20: sofifa_country_flag, 21: sofifa_country_position, 22: normalized_name_sof, 23: normalized_nationality_sof, 24: name_first_letter_sof, 25: match_status, 26: normalized_nationality, 27: clean_dob_sswy, 28: clean_dob_sof, 29: name_first_letter, 30: name_initial, 31: normalized_name_sofifa, 32: clean_dob_sofifa, 33: match_type, 34: normalized_nationality_sofifa, 35: name_first_letter_sofifa) have mixed types. Specify dtype option on import or set low_memory=False.
  df_matched = pd.read_csv("newdata/players/matched/FINAL_MATCHED_MASTER.csv")
C:\Users\ashwy\AppData\Local\Temp\ipykernel_15664\2001095214.py:12: DtypeWarning: Columns (0: sofifa_fifa_update_date, 1: sofifa_value, 2: sofifa_wage, 3: sofifa_club_contract_valid_until, 4: sofifa_weak_foot, 5: sofifa_moves, 6: sofifa_work_rate, 7: sofifa_release_clause, 8: sofifa_agility, 9: sofifa_balance, 10: sofifa_gk_positioning, 11: sofifa_version, 12: sofifa_club_logo, 13: sofifa_country_league_id, 14: sofifa_country_league_name, 15: sofifa_country_flag, 16: sofifa_country_position) have mixed types. Specify dtype option on import or set low_memory=False.
  df_unmatched_sofifa = pd.read_csv("newdata/players/no match/UNMATCHED_SOFIFA.csv")

Extracted 15218 verified Team-to-Club pairings from Master.

==================================================
STARTING SNOWBALL RESCUE ENGINE RUN
==================================================

Processing Season [1/7]: 2019-2020
 -> Total records in season: 1415
 -> VIP Bypass matches found: 258
 -> Running fallback heuristics on remaining 1157 rows...
    - REJECTED: 688
    - TEAM_ANCHOR: 469

Processing Season [2/7]: 2020-2021
 -> Total records in season: 1379
 -> VIP Bypass matches found: 529
 -> Running fallback heuristics on remaining 850 rows...
    - REJECTED: 635
    - TEAM_ANCHOR: 215

Processing Season [3/7]: 2021-2022
 -> Total records in season: 1384
 -> VIP Bypass matches found: 562
 -> Running fallback heuristics on remaining 822 rows...
    - REJECTED: 622
    - TEAM_ANCHOR: 200

Processing Season [4/7]: 2022-2023
 -> Total records in season: 1495
 -> VIP Bypass matches found: 555
 -> Running fallback heuristics on remaining 940 rows...
    - REJECTED: 750
    - TEAM_ANCHOR: 190

Processing Season [5/7]: 2023-2024
 -> Total records in season: 2698
 -> VIP Bypass matches found: 1565
 -> Running fallback heuristics on remaining 1133 rows...
    - TEAM_ANCHOR: 909
    - REJECTED: 224

Processing Season [6/7]: 2024-2025
 -> Total records in season: 3368
 -> VIP Bypass matches found: 2703
 -> Running fallback heuristics on remaining 665 rows...
    - TEAM_ANCHOR: 480
    - REJECTED: 185

Processing Season [7/7]: 2025-2026
 -> Total records in season: 1002
 -> VIP Bypass matches found: 344
 -> Running fallback heuristics on remaining 658 rows...
    - REJECTED: 548
    - TEAM_ANCHOR: 110

==================================================
RUNNING RETROACTIVE SWEEP (TIME MACHINE)
==================================================
Initial rejected rows across all seasons: 3652
 -> Successfully rescued via Retroactive Matured Dictionary: 142

==================================================
FINAL PIPELINE EXECUTION SUMMARY
==================================================
rescue_status
VIP_BYPASS            6516
TEAM_ANCHOR           2573
RETROACTIVE_RESCUE     142
Name: count, dtype: int64
Total True False-Positives (Sent to Unmatched): 3510
==================================================

Saving updated Master and Unmatched files...

PermissionError: [Errno 13] Permission denied: 'newdata/players/partial match/FINAL_PARTIAL_REVIEW.csv'

In [4]:
pd.DataFrame(list(rolling_id_dictionary.items()), columns=['soccersolver_id', 'sofifa_player_id']).to_csv("newdata/players/matched/FINAL_ID_DICTIONARY.csv", index=False)

In [5]:
# ==============================================================================
# 1. LOAD FINAL FILES
# ==============================================================================
print("Loading final datasets for diagnostic report...")
try:
    df_matched = pd.read_csv("newdata/players/matched/FINAL_MATCHED_MASTER.csv")
    df_partial = pd.read_csv("newdata/players/partial match/FINAL_PARTIAL_REVIEW.csv")
    df_unmatched_sswy = pd.read_csv("newdata/players/no match/UNMATCHED_SSWY.csv")
    df_unmatched_sofifa = pd.read_csv("newdata/players/no match/UNMATCHED_SOFIFA.csv")
    dict_df = pd.read_csv("newdata/players/matched/FINAL_ID_DICTIONARY.csv")
except FileNotFoundError as e:
    print(f"Error loading files: {e}")
    exit()

# ==============================================================================
# 2. CALCULATE METRICS
# ==============================================================================
total_matched = len(df_matched)
total_partial = len(df_partial)
total_unmatched_sswy = len(df_unmatched_sswy)
total_unmatched_sofifa = len(df_unmatched_sofifa)
dictionary_size = len(dict_df)

# Breakdown of Match Types in the Master File
if 'match_type' in df_matched.columns:
    match_breakdown = df_matched['match_type'].value_counts().to_dict()
else:
    match_breakdown = {"Unknown/Legacy": total_matched}

# ==============================================================================
# 3. PRINT FORMATTED REPORT
# ==============================================================================
print("\n" + "=" * 80)
print("                 FINAL SYSTEM STATE DIAGNOSTIC REPORT                   ")
print("=" * 80)

print("\n1. MASTER FILE HEALTH (SUCCESSFUL MATCHES)")
print("-" * 80)
print(f" -> TOTAL RESOLVED PLAYERS       : {total_matched:,}")
print(f" -> Master Rolling ID Dictionary : {dictionary_size:,} unique mappings")
print("\n -> Breakdown by Routing Logic:")
for m_type, count in match_breakdown.items():
    # Formatting to keep it aligned nicely
    print(f"    ├── {m_type:<30}: {count:>8,}")

print("\n2. THE PARTIAL FILE (PENDING REVIEW)")
print("-" * 80)
if total_partial == 0:
    print(" -> TOTAL PARTIAL PLAYERS        : 0 (File Successfully Drained)")
else:
    print(f" -> TOTAL PARTIAL PLAYERS        : {total_partial:,} (Needs Review)")

print("\n3. UNMATCHED FILES (REMAINING POOL)")
print("-" * 80)
print(f" -> SSWY Unmatched               : {total_unmatched_sswy:,}")
print(f" -> Sofifa Unmatched             : {total_unmatched_sofifa:,}")

print("\n" + "=" * 80)
print("End of Report.")
print("=" * 80 + "\n")

Loading final datasets for diagnostic report...

C:\Users\ashwy\AppData\Local\Temp\ipykernel_15664\2589958709.py:6: DtypeWarning: Columns (0: clean_dob, 1: sofifa_fifa_update_date, 2: sofifa_value, 3: sofifa_wage, 4: sofifa_club_loaned_from, 5: sofifa_club_contract_valid_until, 6: sofifa_nation_position, 7: sofifa_weak_foot, 8: sofifa_moves, 9: sofifa_international_reputation, 10: sofifa_work_rate, 11: sofifa_release_clause, 12: sofifa_play_styles, 13: sofifa_agility, 14: sofifa_balance, 15: sofifa_gk_positioning, 16: sofifa_version, 17: sofifa_club_logo, 18: sofifa_country_league_id, 19: sofifa_country_league_name, 20: sofifa_country_flag, 21: sofifa_country_position, 22: normalized_name_sof, 23: normalized_nationality_sof, 24: name_first_letter_sof, 25: match_status, 26: normalized_nationality, 27: clean_dob_sswy, 28: clean_dob_sof, 29: name_first_letter, 30: name_initial, 31: normalized_name_sofifa, 32: clean_dob_sofifa, 33: match_type, 34: normalized_nationality_sofifa, 35: name_first_letter_sofifa) have mixed types. Specify dtype option on import or set low_memory=False.
  df_matched = pd.read_csv("newdata/players/matched/FINAL_MATCHED_MASTER.csv")
C:\Users\ashwy\AppData\Local\Temp\ipykernel_15664\2589958709.py:7: DtypeWarning: Columns (0: normalized_nationality_sswy, 1: clean_dob, 2: name_first_letter_sswy, 3: sofifa_value, 4: sofifa_wage, 5: sofifa_club_contract_valid_until, 6: sofifa_weak_foot, 7: sofifa_release_clause, 8: sofifa_agility, 9: sofifa_balance, 10: sofifa_gk_positioning, 11: sofifa_version, 12: sofifa_club_logo, 13: sofifa_country_league_id, 14: sofifa_country_league_name, 15: sofifa_country_flag, 16: sofifa_country_position, 17: normalized_name_sof, 18: normalized_nationality_sof, 19: name_first_letter_sof, 20: match_status, 21: clean_dob_sof, 22: name_initial, 23: normalized_name_sofifa, 24: clean_dob_sofifa, 25: match_type) have mixed types. Specify dtype option on import or set low_memory=False.
  df_partial = pd.read_csv("newdata/players/partial match/FINAL_PARTIAL_REVIEW.csv")

================================================================================
                 FINAL SYSTEM STATE DIAGNOSTIC REPORT
================================================================================

1. MASTER FILE HEALTH (SUCCESSFUL MATCHES)
--------------------------------------------------------------------------------
 -> TOTAL RESOLVED PLAYERS       : 113,454
 -> Master Rolling ID Dictionary : 31,896 unique mappings

 -> Breakdown by Routing Logic:
    ├── RETROACTIVE_RESCUE_SECONDARY  :   10,255
    ├── PARTIAL_RESCUE_VIP_BYPASS     :    6,516
    ├── VIP_BYPASS_SECONDARY          :    5,119
    ├── SECONDARY_HEURISTIC_MATCH     :    3,348
    ├── PARTIAL_RESCUE_TEAM_ANCHOR    :    2,573
    ├── PARTIAL_RESCUE_RETROACTIVE_RESCUE:      142

2. THE PARTIAL FILE (PENDING REVIEW)
--------------------------------------------------------------------------------
 -> TOTAL PARTIAL PLAYERS        : 12,741 (Needs Review)

3. UNMATCHED FILES (REMAINING POOL)
--------------------------------------------------------------------------------
 -> SSWY Unmatched               : 193,334
 -> Sofifa Unmatched             : 24,594

================================================================================
End of Report.
================================================================================

C:\Users\ashwy\AppData\Local\Temp\ipykernel_15664\2589958709.py:9: DtypeWarning: Columns (0: sofifa_fifa_update_date, 1: sofifa_value, 2: sofifa_wage, 3: sofifa_club_contract_valid_until, 4: sofifa_nation_position, 5: sofifa_weak_foot, 6: sofifa_moves, 7: sofifa_work_rate, 8: sofifa_release_clause, 9: sofifa_specialities, 10: sofifa_agility, 11: sofifa_balance, 12: sofifa_gk_positioning, 13: sofifa_version, 14: sofifa_club_logo, 15: sofifa_country_league_id, 16: sofifa_country_league_name, 17: sofifa_country_flag, 18: sofifa_country_position, 19: normalized_name, 20: normalized_nationality, 21: clean_dob, 22: name_first_letter) have mixed types. Specify dtype option on import or set low_memory=False.
  df_unmatched_sofifa = pd.read_csv("newdata/players/no match/UNMATCHED_SOFIFA.csv")