In [1]:
import pandas as pd
file="C:/Users/ashwy/Downloads/male_players.csv"
df=pd.read_csv(file)

print(df.info())
display(df.head())

C:\Users\ashwy\AppData\Local\Temp\ipykernel_37344\1619314098.py:3: DtypeWarning: Columns (0: gk) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(file)

<class 'pandas.DataFrame'>
RangeIndex: 10003590 entries, 0 to 10003589
Columns: 110 entries, player_id to player_face_url
dtypes: float64(18), int64(45), object(1), str(46)
memory usage: 11.1+ GB
None

,player_id,player_url,fifa_version,fifa_update,fifa_update_date,short_name,long_name,player_positions,overall,potential,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url
0,158023,/player/158023/lionel-messi/230009,23,9,2023-01-13,L. Messi,Lionel Andrés Messi Cuccittini,RW,91,91,...,63+3,63+3,64+3,59+3,50+3,50+3,50+3,59+3,19+3,https://cdn.sofifa.net/players/158/023/23_120.png
1,165153,/player/165153/karim-benzema/230009,23,9,2023-01-13,K. Benzema,Karim Benzema,"CF, ST",91,91,...,64+3,64+3,64+3,60+3,55+3,55+3,55+3,60+3,18+3,https://cdn.sofifa.net/players/165/153/23_120.png
2,188545,/player/188545/robert-lewandowski/230009,23,9,2023-01-13,R. Lewandowski,Robert Lewandowski,ST,91,91,...,66+3,66+3,64+3,61+3,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/23_120.png
3,192985,/player/192985/kevin-de-bruyne/230009,23,9,2023-01-13,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,...,79+3,79+3,78+3,74+3,68+3,68+3,68+3,74+3,21+3,https://cdn.sofifa.net/players/192/985/23_120.png
4,231747,/player/231747/kylian-mbappe/230009,23,9,2023-01-13,K. Mbappé,Kylian Mbappé Lottin,"ST, LW",91,95,...,63+3,63+3,67+3,63+3,54+3,54+3,54+3,63+3,18+3,https://cdn.sofifa.net/players/231/747/23_120.png

In [2]:
print(df['fifa_version'].dtype)

int64

In [3]:
print(len(df[df['fifa_version']==23]))

166674

In [6]:
season_23=df[df['fifa_version']==23]
season_23.to_csv('data/sofifa/newdata/players/RAW/fc23.csv',index=False)

## RAW FILES

In [2]:
#File Paths
import pandas as pd
RAW_PLAYERS='data/sofifa/newdata/players/RAW/'
fc26=pd.read_csv(f'{RAW_PLAYERS}FC26.csv')
fc25=pd.read_csv(f'{RAW_PLAYERS}fc25.csv')
fc24=pd.read_csv(f'{RAW_PLAYERS}FC24.csv')
fifa23=pd.read_csv(f'{RAW_PLAYERS}fc23.csv')
fifa22=pd.read_csv(f'{RAW_PLAYERS}players_22.csv')
fifa21=pd.read_csv(f'{RAW_PLAYERS}players_21.csv')
fifa20=pd.read_csv(f'{RAW_PLAYERS}players_20.csv')

df_list=[fc26,fc25,fc24,fifa23,fifa22,fifa21,fifa20]
for df in df_list:
    print(df.shape)
    print(df.columns.tolist())
    print('-'*50)

C:\Users\ashwy\AppData\Local\Temp\ipykernel_9376\1086894509.py:4: DtypeWarning: Columns (0: player_tags) have mixed types. Specify dtype option on import or set low_memory=False.
  fc26=pd.read_csv(f'{RAW_PLAYERS}FC26.csv')
C:\Users\ashwy\AppData\Local\Temp\ipykernel_9376\1086894509.py:5: DtypeWarning: Columns (0: international_reputation) have mixed types. Specify dtype option on import or set low_memory=False.
  fc25=pd.read_csv(f'{RAW_PLAYERS}fc25.csv')
C:\Users\ashwy\AppData\Local\Temp\ipykernel_9376\1086894509.py:6: DtypeWarning: Columns (0: weak_foot, 1: skill_moves, 2: country_name, 3: country_league_id, 4: country_league_name, 5: country_flag, 6: country_position, 7: gk_positioning) have mixed types. Specify dtype option on import or set low_memory=False.
  fc24=pd.read_csv(f'{RAW_PLAYERS}FC24.csv')
C:\Users\ashwy\AppData\Local\Temp\ipykernel_9376\1086894509.py:8: DtypeWarning: Columns (0: nation_position, 1: nation_logo_url) have mixed types. Specify dtype option on import or set low_memory=False.
  fifa22=pd.read_csv(f'{RAW_PLAYERS}players_22.csv')

(18405, 110)
['player_id', 'player_url', 'fifa_version', 'fifa_update', 'fifa_update_date', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'league_id', 'league_name', 'league_level', 'club_team_id', 'club_name', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined_date', 'club_contract_valid_until_year', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url']
--------------------------------------------------
(18205, 76)
['player_id', 'version', 'name', 'full_name', 'description', 'image', 'height_cm', 'weight_kg', 'dob', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'club_id', 'club_name', 'club_league_id', 'club_league_name', 'club_logo', 'club_rating', 'club_position', 'club_kit_number', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'country_league_id', 'country_league_name', 'country_flag', 'country_rating', 'country_position', 'country_kit_number', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'play_styles']
--------------------------------------------------
(18331, 76)
['player_id', 'version', 'name', 'full_name', 'description', 'image', 'height_cm', 'weight_kg', 'dob', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'club_id', 'club_name', 'club_league_id', 'club_league_name', 'club_logo', 'club_rating', 'club_position', 'club_kit_number', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'country_league_id', 'country_league_name', 'country_flag', 'country_rating', 'country_position', 'country_kit_number', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'play_styles']
--------------------------------------------------
(166674, 110)
['player_id', 'player_url', 'fifa_version', 'fifa_update', 'fifa_update_date', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'league_id', 'league_name', 'league_level', 'club_team_id', 'club_name', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined_date', 'club_contract_valid_until_year', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url']
--------------------------------------------------
(19239, 110)
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url']
--------------------------------------------------
(18944, 110)
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url']
--------------------------------------------------
(18483, 110)
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url']
--------------------------------------------------

In [3]:
import pandas as pd

def prune_datasets(df_list):
    """
    Strips noise, text, and granular positional ratings from a list of dataframes.
    """
    # Phase 1 Drop Targets
    url_image_cols = [
        'player_url', 'player_face_url', 'club_logo_url', 
        'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'image'
    ]
    
    text_cols = ['description']
    
    positional_ratings = [
        'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 
        'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 
        'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk'
    ]
    
    # Combine all targets into a single master drop list
    cols_to_drop = url_image_cols + text_cols + positional_ratings
    
    # Execute drop across all dataframes in-place
    for i in range(len(df_list)):
        df_list[i].drop(columns=cols_to_drop, errors='ignore', inplace=True)
        print(f"Dataset {i+1} reduced to {len(df_list[i].columns)} columns.")
        
    return df_list

df_list = prune_datasets(df_list)

for df in df_list:
    print(df.shape)
    print(df.columns.tolist())
    print('-'*50)

Dataset 1 reduced to 81 columns.
Dataset 2 reduced to 74 columns.
Dataset 3 reduced to 74 columns.
Dataset 4 reduced to 81 columns.
Dataset 5 reduced to 77 columns.
Dataset 6 reduced to 77 columns.
Dataset 7 reduced to 77 columns.
(18405, 81)
['player_id', 'fifa_version', 'fifa_update', 'fifa_update_date', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'league_id', 'league_name', 'league_level', 'club_team_id', 'club_name', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined_date', 'club_contract_valid_until_year', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']
--------------------------------------------------
(18205, 74)
['player_id', 'version', 'name', 'full_name', 'height_cm', 'weight_kg', 'dob', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'club_id', 'club_name', 'club_league_id', 'club_league_name', 'club_logo', 'club_rating', 'club_position', 'club_kit_number', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'country_league_id', 'country_league_name', 'country_flag', 'country_rating', 'country_position', 'country_kit_number', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'play_styles']
--------------------------------------------------
(18331, 74)
['player_id', 'version', 'name', 'full_name', 'height_cm', 'weight_kg', 'dob', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'club_id', 'club_name', 'club_league_id', 'club_league_name', 'club_logo', 'club_rating', 'club_position', 'club_kit_number', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'country_league_id', 'country_league_name', 'country_flag', 'country_rating', 'country_position', 'country_kit_number', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'play_styles']
--------------------------------------------------
(166674, 81)
['player_id', 'fifa_version', 'fifa_update', 'fifa_update_date', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'league_id', 'league_name', 'league_level', 'club_team_id', 'club_name', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined_date', 'club_contract_valid_until_year', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']
--------------------------------------------------
(19239, 77)
['sofifa_id', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']
--------------------------------------------------
(18944, 77)
['sofifa_id', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']
--------------------------------------------------
(18483, 77)
['sofifa_id', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed']
--------------------------------------------------

In [4]:
import pandas as pd

def standardize_schema(df_list):
    """
    Unifies dataset columns to the concise 76-column schema naming convention.
    """
    # 1. Explicit mapping for core identifiers, financials, and team data
    master_mapping = {
        'sofifa_id': 'player_id',
        'short_name': 'name',
        'long_name': 'full_name',
        'player_positions': 'positions',
        'overall': 'overall_rating',
        'value_eur': 'value',
        'wage_eur': 'wage',
        'release_clause_eur': 'release_clause',
        'club_team_id': 'club_id',
        'league_name': 'club_league_name',
        'club_jersey_number': 'club_kit_number',
        'club_joined_date': 'club_joined',
        'club_contract_valid_until_year': 'club_contract_valid_until',
        'nationality_id': 'country_id',
        'nationality_name': 'country_name',
        'nation_jersey_number': 'country_kit_number',
        'player_tags': 'specialities',
        'player_traits': 'play_styles',
        # Edge cases explicitly defined
        'defending_marking_awareness': 'defensive_awareness',
        'goalkeeping_diving': 'gk_diving',
        'goalkeeping_handling': 'gk_handling',
        'goalkeeping_kicking': 'gk_kicking',
        'goalkeeping_positioning': 'gk_positioning',
        'goalkeeping_reflexes': 'gk_reflexes',
        'goalkeeping_speed': 'gk_speed'
    }

    # 2. Prefixes to dynamically strip from granular attributes
    prefixes_to_strip = [
        'attacking_', 'skill_', 'movement_', 
        'power_', 'mentality_', 'defending_'
    ]

    for i, df in enumerate(df_list):
        # NEW FIX: Isolate the macro dribbling stat before stripping prefixes
        if 'skill_dribbling' in df.columns and 'dribbling' in df.columns:
            df.rename(columns={'dribbling': 'macro_dribbling'}, inplace=True)

        # Apply the explicit master dictionary
        df.rename(columns=master_mapping, inplace=True)
        
        # Dynamically strip the prefixes from the remaining 110-col schemas
        new_columns = {}
        for col in df.columns:
            for prefix in prefixes_to_strip:
                if col.startswith(prefix):
                    new_columns[col] = col.replace(prefix, '')
                    break # Stop checking prefixes once a match is found
        
        df.rename(columns=new_columns, inplace=True)
        print(f"Dataset {i+1} schema standardized. Current column count: {len(df.columns)}")

    return df_list


df_list = standardize_schema(df_list)
def df_check():
    for df in df_list:
        print(df.shape)
        print(df.columns.tolist())
        print('-'*50)

df_check()

Dataset 1 schema standardized. Current column count: 81
Dataset 2 schema standardized. Current column count: 74
Dataset 3 schema standardized. Current column count: 74
Dataset 4 schema standardized. Current column count: 81
Dataset 5 schema standardized. Current column count: 77
Dataset 6 schema standardized. Current column count: 77
Dataset 7 schema standardized. Current column count: 77
(18405, 81)
['player_id', 'fifa_version', 'fifa_update', 'fifa_update_date', 'name', 'full_name', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'age', 'dob', 'height_cm', 'weight_kg', 'league_id', 'club_league_name', 'league_level', 'club_id', 'club_name', 'club_position', 'club_kit_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'nation_team_id', 'nation_position', 'country_kit_number', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'play_styles', 'pace', 'shooting', 'passing', 'macro_dribbling', 'defending', 'physic', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'gk_speed']
--------------------------------------------------
(18205, 74)
['player_id', 'version', 'name', 'full_name', 'height_cm', 'weight_kg', 'dob', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'club_id', 'club_name', 'club_league_id', 'club_league_name', 'club_logo', 'club_rating', 'club_position', 'club_kit_number', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'country_league_id', 'country_league_name', 'country_flag', 'country_rating', 'country_position', 'country_kit_number', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'play_styles']
--------------------------------------------------
(18331, 74)
['player_id', 'version', 'name', 'full_name', 'height_cm', 'weight_kg', 'dob', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'club_id', 'club_name', 'club_league_id', 'club_league_name', 'club_logo', 'club_rating', 'club_position', 'club_kit_number', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'country_league_id', 'country_league_name', 'country_flag', 'country_rating', 'country_position', 'country_kit_number', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'play_styles']
--------------------------------------------------
(166674, 81)
['player_id', 'fifa_version', 'fifa_update', 'fifa_update_date', 'name', 'full_name', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'age', 'dob', 'height_cm', 'weight_kg', 'league_id', 'club_league_name', 'league_level', 'club_id', 'club_name', 'club_position', 'club_kit_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'nation_team_id', 'nation_position', 'country_kit_number', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'play_styles', 'pace', 'shooting', 'passing', 'macro_dribbling', 'defending', 'physic', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'gk_speed']
--------------------------------------------------
(19239, 77)
['player_id', 'name', 'full_name', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'age', 'dob', 'height_cm', 'weight_kg', 'club_id', 'club_name', 'club_league_name', 'league_level', 'club_position', 'club_kit_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'nation_team_id', 'nation_position', 'country_kit_number', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'play_styles', 'pace', 'shooting', 'passing', 'macro_dribbling', 'defending', 'physic', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'gk_speed']
--------------------------------------------------
(18944, 77)
['player_id', 'name', 'full_name', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'age', 'dob', 'height_cm', 'weight_kg', 'club_id', 'club_name', 'club_league_name', 'league_level', 'club_position', 'club_kit_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'nation_team_id', 'nation_position', 'country_kit_number', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'play_styles', 'pace', 'shooting', 'passing', 'macro_dribbling', 'defending', 'physic', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'gk_speed']
--------------------------------------------------
(18483, 77)
['player_id', 'name', 'full_name', 'positions', 'overall_rating', 'potential', 'value', 'wage', 'age', 'dob', 'height_cm', 'weight_kg', 'club_id', 'club_name', 'club_league_name', 'league_level', 'club_position', 'club_kit_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'country_id', 'country_name', 'nation_team_id', 'nation_position', 'country_kit_number', 'preferred_foot', 'weak_foot', 'moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause', 'specialities', 'play_styles', 'pace', 'shooting', 'passing', 'macro_dribbling', 'defending', 'physic', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defensive_awareness', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'gk_speed']
--------------------------------------------------

In [5]:
def inject_season_tags(df_list):
    """
    Injects a temporal 'season' column into each dataframe to track 
    chronological data before concatenation.
    """
    # Define the season labels matching the exact order of your dataframes
    # (Ordered from newest to oldest: 25/26 -> 19/20)
    season_labels = [
        '2025-2026', '2024-2025', '2023-2024', 
        '2022-2023', '2021-2022', '2020-2021', '2019-2020'
    ]
    
    # Iterate through the list and broadcast the string to a new column
    for i, df in enumerate(df_list):
        df['season'] = season_labels[i]
        print(f"Dataset {i+1} temporally tagged as: {season_labels[i]}")
        
    return df_list

# Execution:
df_list = inject_season_tags(df_list)

Dataset 1 temporally tagged as: 2025-2026
Dataset 2 temporally tagged as: 2024-2025
Dataset 3 temporally tagged as: 2023-2024
Dataset 4 temporally tagged as: 2022-2023
Dataset 5 temporally tagged as: 2021-2022
Dataset 6 temporally tagged as: 2020-2021
Dataset 7 temporally tagged as: 2019-2020

In [6]:
for df in df_list:
    display(df.head())

,player_id,fifa_version,fifa_update,fifa_update_date,name,full_name,positions,overall_rating,potential,value,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,gk_speed,season
0,252371,26,4,2025-09-19,J. Bellingham,Jude Victor William Bellingham,"CAM, CM",90,94,174500000,...,77,79,77,14,11,10,5,8,NaN,2025-2026
1,239053,26,4,2025-09-19,F. Valverde,Federico Santiago Valverde Dipetta,"CM, CDM, RB",89,90,120500000,...,82,87,86,6,10,6,15,8,NaN,2025-2026
2,212622,26,4,2025-09-19,J. Kimmich,Joshua Walter Kimmich,"CDM, RB, CM",89,89,86000000,...,82,86,85,8,15,7,15,15,NaN,2025-2026
3,235212,26,4,2025-09-19,A. Hakimi,Achraf Hakimi Mouhأشرف حكيمي,"RB, RM",89,90,111000000,...,82,85,79,10,8,14,6,8,NaN,2025-2026
4,224232,26,4,2025-09-19,N. Barella,Nicolò Barella,CM,87,87,79500000,...,80,85,80,11,5,13,14,11,NaN,2025-2026

,player_id,version,name,full_name,height_cm,weight_kg,dob,positions,overall_rating,potential,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,play_styles,season
0,231866,2025-06-03,Rodri -,Rodrigo Hernández Cascante,190,82,1996-06-22,"CDM,CM",91,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-2025
1,209331,2025-06-03,Mohamed Salah Hamed Ghaly -,Mohamed Salah Hamed Ghalyمحمد صلاح,175,72,1992-06-15,"RM,RW",91,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-2025
2,252371,2025-06-03,Jude Victor William Bellingham -,Jude Victor William Bellingham,186,75,2003-06-29,"CAM,CM",90,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-2025
3,239085,2025-06-03,Erling Braut Håland -,Erling Braut Håland,195,94,2000-07-21,ST,90,92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-2025
4,238794,2025-06-03,Vini Jr. -,Vinicius José Paixão de Oliveira Junior,176,73,2000-07-12,"LW,ST",90,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-2025

,player_id,version,name,full_name,height_cm,weight_kg,dob,positions,overall_rating,potential,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,play_styles,season
0,239085,240033,Erling Haaland,Erling Braut Haaland,195,94,2000-07-21,ST,91,94,...,38,47,29,7,14,13,11,7.0,"Acrobatic +,Power Header,Quick Step",2023-2024
1,231747,240033,Kylian Mbappé,Kylian Mbappé Lottin,182,75,1998-12-20,"ST,LW",91,94,...,26,34,32,13,5,7,11,6.0,"Quick Step +,Finesse Shot,Rapid,Flair,Trivela,...",2023-2024
2,192985,240033,Kevin De Bruyne,Kevin De Bruyne,181,75,1991-06-28,"CM,CAM",91,91,...,66,70,53,15,13,5,10,13.0,"Incisive Pass +,Dead Ball,Pinged Pass,Long Bal...",2023-2024
3,231866,240033,Rodri,Rodrigo Hernández Cascante,191,82,1996-06-22,"CDM,CM",90,91,...,92,87,78,10,10,7,14,8.0,"Power Shot +,Long Ball Pass,Bruiser,Aerial",2023-2024
4,202126,240033,Harry Kane,Harry Kane,188,85,1993-07-28,ST,90,90,...,46,46,38,8,10,11,14,11.0,"Incisive Pass +,Long Ball Pass,First Touch,Tri...",2023-2024

,player_id,fifa_version,fifa_update,fifa_update_date,name,full_name,positions,overall_rating,potential,value,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,gk_speed,season
0,158023,23,9,2023-01-13,L. Messi,Lionel Andrés Messi Cuccittini,RW,91,91,54000000.0,...,20,35,24,6,11,15,14,8,NaN,2022-2023
1,165153,23,9,2023-01-13,K. Benzema,Karim Benzema,"CF, ST",91,91,64000000.0,...,43,24,18,13,11,5,5,7,NaN,2022-2023
2,188545,23,9,2023-01-13,R. Lewandowski,Robert Lewandowski,ST,91,91,84000000.0,...,35,42,19,15,6,12,8,10,NaN,2022-2023
3,192985,23,9,2023-01-13,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,107500000.0,...,65,65,53,15,13,5,10,13,NaN,2022-2023
4,231747,23,9,2023-01-13,K. Mbappé,Kylian Mbappé Lottin,"ST, LW",91,95,190500000.0,...,26,34,32,13,5,7,11,6,NaN,2022-2023

,player_id,name,full_name,positions,overall_rating,potential,value,wage,age,dob,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,gk_speed,season
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,1987-06-24,...,20,35,24,6,11,15,14,8,NaN,2021-2022
1,188545,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,1988-08-21,...,35,42,19,15,6,12,8,10,NaN,2021-2022
2,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,1985-02-05,...,24,32,24,7,11,15,14,11,NaN,2021-2022
3,190871,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,1992-02-05,...,35,32,29,9,9,15,15,11,NaN,2021-2022
4,192985,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,1991-06-28,...,68,65,53,15,13,5,10,13,NaN,2021-2022

,player_id,name,full_name,positions,overall_rating,potential,value,wage,age,dob,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,gk_speed,season
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,103500000.0,560000.0,33,1987-06-24,...,32,35,24,6,11,15,14,8,NaN,2020-2021
1,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",92,92,63000000.0,220000.0,35,1985-02-05,...,28,32,24,7,11,15,14,11,NaN,2020-2021
2,188545,R. Lewandowski,Robert Lewandowski,ST,91,91,111000000.0,240000.0,31,1988-08-21,...,35,42,19,15,6,12,8,10,NaN,2020-2021
3,190871,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,132000000.0,270000.0,28,1992-02-05,...,35,30,29,9,9,15,15,11,NaN,2020-2021
4,192985,K. De Bruyne,Kevin De Bruyne,"CAM, CM",91,91,129000000.0,370000.0,29,1991-06-28,...,68,65,53,15,13,5,10,13,NaN,2020-2021

,player_id,name,full_name,positions,overall_rating,potential,value,wage,age,dob,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,gk_speed,season
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,"RW, CF, ST",94,94,95500000.0,560000.0,32,1987-06-24,...,33,37,26,6,11,15,14,8,NaN,2019-2020
1,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",93,93,58500000.0,410000.0,34,1985-02-05,...,28,32,24,7,11,15,14,11,NaN,2019-2020
2,190871,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",92,92,105500000.0,290000.0,27,1992-02-05,...,27,26,29,9,9,15,15,11,NaN,2019-2020
3,183277,E. Hazard,Eden Hazard,"LW, CF",91,91,90000000.0,470000.0,28,1991-01-07,...,34,27,22,11,12,6,8,8,NaN,2019-2020
4,192985,K. De Bruyne,Kevin De Bruyne,"CAM, CM",91,91,90000000.0,370000.0,28,1991-06-28,...,68,58,51,15,13,5,10,13,NaN,2019-2020

In [7]:
def build_master_dataset(df_list):
    """
    Executes the inner join stack, removes duplicates, and generates 
    a diagnostic report of dropped columns per season.
    """
    season_labels = [
        '2025-2026', '2024-2025', '2023-2024', 
        '2022-2023', '2021-2022', '2020-2021', '2019-2020'
    ]
    
    # Store the original column sets before the inner join destroys them
    original_cols = [set(df.columns) for df in df_list]
    
    # Step 2: Inner Join Concatenation
    print("Executing Outer Join...")
    master_df = pd.concat(df_list, join='outer', ignore_index=True)
    master_col_set = set(master_df.columns)
    
    # Generate Drop Report via Set Difference
    print("\n--- Column Drop Diagnostic Report ---")
    for i, orig_set in enumerate(original_cols):
        dropped_cols = orig_set - master_col_set
        if dropped_cols:
            print(f"Season {season_labels[i]} dropped {len(dropped_cols)} columns:")
            # Sorting for readability in the terminal
            print(f" -> {sorted(list(dropped_cols))}\n")
        else:
            print(f"Season {season_labels[i]} dropped 0 columns.\n")
            
    # Step 3: Anomaly Resolution
    rows_before = len(master_df)
    master_df.drop_duplicates(subset=['player_id', 'season'], keep='first', inplace=True)
    rows_after = len(master_df)
    
    # Step 4: Index Reset
    master_df.reset_index(drop=True, inplace=True)
    
    # Final Output Summary
    print("--- Final Pipeline Stats ---")
    print(f"Rows dropped during deduplication (22/23 anomaly): {rows_before - rows_after}")
    print(f"Final Master Dataset Shape: {master_df.shape}")
    print(f"Uniform Features Available: {len(master_df.columns)}")
    
    return master_df

In [8]:
# Execution:
master_df = build_master_dataset(df_list)

Executing Outer Join...

--- Column Drop Diagnostic Report ---
Season 2025-2026 dropped 0 columns.

Season 2024-2025 dropped 0 columns.

Season 2023-2024 dropped 0 columns.

Season 2022-2023 dropped 0 columns.

Season 2021-2022 dropped 0 columns.

Season 2020-2021 dropped 0 columns.

Season 2019-2020 dropped 0 columns.

--- Final Pipeline Stats ---
Rows dropped during deduplication (22/23 anomaly): 146112
Final Master Dataset Shape: (132169, 91)
Uniform Features Available: 91

In [10]:
# 1. Verify the shape of the 22/23 season data inside the master dataframe
shape_22_23 = master_df[master_df['season'] == '2022-2023'].shape
print(f"Verified 2022/23 Season Shape: {shape_22_23}")

# 2. Export the final unified dataset to a CSV file
export_filename = 'data/sofifa/newdata/players/CLEANED/SOFIFA_PLAYERS.csv'
master_df.to_csv(export_filename, index=False)
print(f"Export complete. File saved as: {export_filename}")

Verified 2022/23 Season Shape: (20621, 91)
Export complete. File saved as: data/sofifa/newdata/players/CLEANED/SOFIFA_PLAYERS.csv